-- ================================================================ Chinese (Simplified) / 简体中文
-- The panel's text in Simplified Chinese. Translation by hd2modpj, from their
-- "Super Earth Armory Forge 简体中文" addon (ported into the mod in 6.2): official game
-- names for passives and armors (the game's own schinese text), the rest translated for the
-- panel. PP.tr in panel.lua looks things up here: ui / perk / effect / unit / preset / desc /
-- armor are whole strings (any case), pat are sentences with numbers or names in them,
-- frag are pieces replaced inside other text. fallback: ASCII stand-ins for punctuation the
-- game font has no glyph for. Missing strings simply stay English.
local LANGS = LANGS or {}
LANGS.zh = {
    name = '简体中文',
    credit = 'hd2modpj',
    ui = {
        -- 顶栏
        ['MINISTRY OF DEFENSE']        = '国防部',
        ['SUPER EARTH ARMORY FORGE']   = '超级地球军械工坊',
        ['SIZE']                       = '尺寸',
        ['DRAG TO MOVE']               = '拖动此处移动面板',
        ['ARMORY']                     = '军械',
        ['FORGE']                      = '工坊',
        ['Tick passives, change values: it all applies at once.'] = '勾选被动、改动数值：全部即时生效。',
        -- 底部按键条
        ['Close']                      = '关闭',
        ['Undo']                       = '撤销',
        ['Swap loadout']               = '切换配装',
        ['SOLO / PRIVATE LOBBIES ONLY'] = '仅限单人 / 私人房间',
        -- 扫描中
        ['Scanning armory records']    = '正在扫描军械记录',
        ['Load into your ship or a mission if this does not finish.'] = '若长时间未完成，请进入飞船或任务。',
        -- 标签页
        ['+ Armor']                    = '+ 护甲',
        ['Presets']                    = '预设',
        ['REMOVE THIS STACK']          = '移除此堆叠',
        ['CLICK AGAIN TO REMOVE']      = '再次点击以移除',
        -- 预设页
        ['Loadouts']                   = '配装',
        ['Standard issue']             = '标准配发',
        ['Your loadouts']              = '我的配装',
        ['None yet. Save the current stack.'] = '还没有。把当前堆叠存下来吧。',
        ['+ Save current stack']       = '+ 保存当前堆叠',
        ['Choose a preset']            = '选择一个预设',
        ['Pick one on the left to see what it stacks, then load it.'] = '在左边选一个，看看它叠了什么，然后载入。',
        ['Save your own with "+ Save current stack".'] = '用「+ 保存当前堆叠」存你自己的。',
        ['Installed build']            = '安装时的配装',
        ['Your loadout']               = '我的配装',
        ['Load this preset']           = '载入此预设',
        ['Click again']                = '再点一次',
        ['Save current here']          = '把当前堆叠存到这里',
        ['Rename']                     = '重命名',
        ['Delete']                     = '删除',
        ['Type a name, Enter to keep it, Esc to cancel.'] = '输入名称，回车保存，Esc 取消。',
        ['Loading replaces your current stacks (Undo brings them back).'] = '载入会替换当前堆叠（撤销可以找回）。',
        -- 新增护甲页
        ['New stack']                  = '新堆叠',
        ['Choose armor passive']       = '选择护甲被动',
        ['Cancel']                     = '取消',
        ['A second stack']             = '第二个堆叠',
        ['Each armor passive can carry its own stack. Pick one on the left,'] = '每个护甲被动都可以有自己的堆叠。在左边选一个，',
        ['then wear any armor that has that passive to get the stack.'] = '然后穿上带该被动的护甲即可获得这套堆叠。',
        ['Example: Med-Kit armor for a tank build, Siege-Ready armor for a gunner build.'] = '例如：医疗包护甲配坦克流，攻坚就绪护甲配枪手流。',
        -- 空状态
        ['No armor forged yet']        = '还没有打造护甲',
        ['Empty']                      = '空',
        ['Nothing is stacked.']        = '当前没有堆叠任何被动。',
        ['How it works']               = '怎么用',
        ['Forge your armor']           = '打造你的护甲',
        ['Pick the armor passive you wear (for example Med-Kit),'] = '先选中你所穿护甲的被动（例如医疗包），',
        ['then tick any of the 31 passives to stack onto it and'] = '再勾选 31 个被动中的任意几个叠加上去，',
        ['change their values. Everything applies at once.'] = '并改动它们的数值。一切即时生效。',
        -- 堆叠页
        ['Choose passives']            = '选择被动',
        ['BASE']                       = '基础',
        ['Specifications']             = '规格参数',
        ['Remove from stack']          = '从堆叠移除',
        ['Add to stack']               = '加入堆叠',
        ['BASE PERK']                  = '基础被动',
        ['STACKED']                    = '已堆叠',
        ['NOT STACKED']                = '未堆叠',
        ["Your armor's own passive. Values here replace its own."] = '这是护甲自带的被动。这里的数值会替换它原本的数值。',
        ['Values you set are kept for when you add it.'] = '你设置的数值会保留，等你把它加进来时生效。',
        ['When two passives change the same thing'] = '当两个被动改动同一项时',
        ['Stack all']                  = '全部叠加',
        ['Strongest only']             = '仅取最强',
        ["This armor passive was not found in the game's data yet."] = '游戏数据里还没找到这个护甲被动。',
        ["Another mod already changed this passive's data; Armory Forge leaves it alone."] = '别的模组已经改过这个被动的数据；本模组不会去动它。',
        ['Copy code']                  = '复制代码',
        ['Paste code']                 = '粘贴代码',
        ['Turn all off']               = '全部关闭',
        -- 提示条消息
        ['Nothing to undo']            = '没有可撤销的操作',
        ['Could not undo']             = '撤销失败',
        ['Turned everything off on this armor'] = '已关闭这件护甲上的全部被动',
        ['Share code copied: paste it in the web builder, or a friend\'s panel'] = '分享代码已复制：粘贴到网页版或朋友的面板里即可',
        ['Could not use the clipboard'] = '无法使用剪贴板',
        ['The clipboard is empty']     = '剪贴板是空的',
        ['No Armory Forge code on the clipboard'] = '剪贴板上没有军械工坊的代码',
        ['That preset could not be read'] = '这个预设读不出来',
        ['Panel back in place']        = '面板已回到默认位置',
        ['ready']                      = '就绪',

        -- ---- 5.4/5.5 新增：标签页与 Keys 页
        ['Keys']                       = '按键',
        ['Settings']                   = '设置',
        ['Panel']                      = '面板',
        ['Remove armor']               = '移除护甲',
        ['Click again to remove']      = '再次点击以移除',
        ['Open / close this panel']    = '打开 / 关闭此面板',
        ['Quick-swap loadouts']        = '快速切换配装',
        ['OFF']                        = '关',
        ['Picking the quick-swap key as the panel key turns quick-swap off.'] = '把快速切换键设成面板键会关闭快速切换。',
        ['Quick-swap key turned off']  = '快速切换键已关闭',
        ['- Smaller']                  = '- 缩小',
        ['+ Bigger']                   = '+ 放大',
        ['Reset size and position']    = '重置大小与位置',
        ['Move the panel: drag its top strip.'] = '移动面板：拖动顶部条即可。',
        ['Taller than the screen: turn the wheel outside a list to scroll it.'] = '面板比屏幕高：在列表外滚动鼠标滚轮即可上下移动。',
        ['Fixed keys']                 = '固定快捷键',
        ['Search passives']            = '搜索被动',
        ['Panel size']                 = '面板尺寸',
        ['Scroll a long list']         = '滚动长列表',
        ['SHODAN Stat Editor uses F8 by default: pick another key here if you run both.'] = 'SHODAN Stat Editor 默认占用 F8：同时使用两个模组的话，请在这里换一个键。',
        ["Keys are saved with your loadout (hotkey / swap_hotkey in loadout.ini)."] = '按键随配装一起保存（loadout.ini 里的 hotkey / swap_hotkey）。',
        -- 搜索（Ctrl+F）
        ['SEARCH PASSIVES OR EFFECTS  (CTRL+F)'] = '搜索被动或效果  (CTRL+F)',
        ['CLEAR']                      = '清除',
        -- 手柄按键提示（Back+Start 开关面板）
        ['Select']                     = '选择',
        ['Back']                       = '返回',
        ['Tabs']                       = '切换标签页',
        ['Tick']                       = '勾选',
        -- 被动说明与实机确认标记（5.5）
        ['Armors with this passive']   = '带此被动的护甲',
        ['Point at a passive to see what it does and which armors have it.'] = '指向一个被动可查看效果，以及哪些护甲带它。',
        ['Picked the wrong one? Open its tab and press REMOVE ARMOR.'] = '选错了？打开它的标签页，点「移除护甲」。',
        ['CONFIRMED IN GAME']          = '游戏内已确认',
        ['WORKS, NAME UNSURE']         = '有效，名称存疑',
        ['NO EFFECT SEEN']             = '未见效果',
        ['UNTESTED']                   = '未测试',
        ['Stack summary']              = '堆叠摘要',
        ['STACK SUMMARY']              = '堆叠摘要',
        ['SUM']                        = '合计',
        ['WGT']                        = '重量',
        -- 6.2.1: Every armor (Armory Forge's own wording)
        ['OWN']                        = '自带',
        ['Any armor you wear']         = '你穿的任何护甲',
        ["The armor's own passive"]    = '护甲自带被动',
        ['Keep it']                    = '保留',
        ['Turn it off']                = '关闭',
        ['On every armor.']            = '作用于所有护甲。',
        ['Off: only the passives you tick count, whatever armor you wear.'] = '关闭：不管穿什么护甲，只有你勾选的被动生效。',
        ['Kept: each armor keeps its own passive, and your stack goes on top.'] = '保留：每件护甲保留自带被动，你的堆叠叠加在上面。',
        ["Tick passives on the left; a passive's own tab (e.g. Med-Kit) still wins for its armors."] = '在左边勾选被动；某个被动自己的标签页（例如医疗包）对它的护甲优先。',
        ['No armor records found yet. Load into your ship or a mission.'] = '还没找到护甲记录。请进入飞船或任务。',
        ['Added an Every armor stack: it stays whatever armor you wear'] = '已添加所有护甲堆叠：不管穿什么护甲都保持不变',
        ["The armors' own passives are off: only your picks count"] = '护甲自带被动已关闭：只有你选的被动生效',
        ['The armors keep their own passives'] = '护甲保留自带被动',
        ['One stack for every armor you wear: pick passives and a weight once, then change armor as often as you like and the stack stays.'] = '一套堆叠适用于你穿的所有护甲：只需选一次被动和重量，之后随便换护甲，堆叠都不变。',
        ["It goes on every armor whose passive has no tab of its own. You can also turn the armors' own passives off, so only your picks count."] = '它会加到所有被动没有自己标签页的护甲上。你也可以关闭护甲自带被动，只让你选的被动生效。',
        ['Nothing stacked yet: tick passives on the left.'] = '还没有叠加被动：在左边勾选即可。',
        -- 被动替换版（Passive Swap edition，Nexus 版）
        ["Passive Swap: give any armor another passive, at the game's values."] = '被动替换：给任意护甲换上另一个被动，数值沿用游戏原值。',
        ['Tick passives to stack them. Click a name to edit its values.'] = '勾选被动即可堆叠。点击名称可编辑数值。',
        ['New swap']                   = '新替换',
        ['Swap passive']               = '替换被动',
        ['Swapped in']                 = '已换上',
        ['its own passive']            = '自带被动',
        ['Original passive']           = '原始被动',
        ['This armor keeps its own passive. Pick another on the left to swap it.'] = '这件护甲保留自带被动。在左边选一个来替换。',
        ['Game values']                = '游戏数值',
        ["The passive is copied from the game's own data. One passive per armor, no stacking."] = '被动直接复制自游戏本身的数据。每件护甲一个被动，不叠加。',
        ["Active: the game's own passive"] = '已生效：游戏自带的被动',
        ['Back to original']           = '恢复原始',
        ['Pick your armor']            = '选择你的护甲',
        ['Pick the passive of the armor you wear on the left,'] = '在左边选中你所穿护甲的被动，',
        ['then choose which passive it should have instead.'] = '再为它选择要换上的被动。',
        ['Example: Med-Kit armor with Siege-Ready.'] = '例如：医疗包护甲换上蓄势出击。',
        ["then choose which of the game's passives it should"] = '再从游戏被动中为它选择要换上的那个，',
        ["have instead. The values are the game's own."] = '数值与游戏原值完全一致。',
        ['Nothing is swapped.']        = '当前没有替换任何被动。',
        ['None yet. Save your current swaps.'] = '还没有。把当前替换存下来吧。',
        ['+ Save current swaps']       = '+ 保存当前替换',
        ['Save your own with "+ Save current swaps".'] = '用「+ 保存当前替换」存你自己的。',
        ['Loading replaces your current swaps (Undo brings them back).'] = '载入会替换当前替换（撤销可找回）。',
        ['Pick it, then choose the passive these armors should have.'] = '选中它，再为这些护甲指定被动。',
        ['Pick it, then wear any of these armors to get the stack.'] = '选中它，然后穿上这些护甲中任意一件即可获得堆叠。',
        -- ---- 5.6/5.7/6.0/6.1 新增：Guide 页 / 重量页 / 报告 / 穿戴框
        ['Guide']                      = '指南',
        ['How to use it']              = '使用方法',
        ['Controls']                   = '操作',
        ['Keyboard']                   = '键盘',
        ['Mouse']                      = '鼠标',
        ['Controller']                 = '手柄',
        ['Wearing']                    = '当前穿戴',
        ['Looking for your armor...']  = '正在寻找你的护甲……',
        ['Shows a few seconds after loading in.'] = '进入游戏几秒后会显示。',
        ['Passive not known to the mod'] = '本模组不认识这个被动',
        ['Recipes']                    = '配方',
        ['RCP']                        = '配方',
        ['Armor passive combos']       = '护甲被动组合',
        ['Pick a recipe to tick all its passives at once. Save your own from what is ticked now.'] = '选一个配方，一次勾选它的所有被动。也可以把当前勾选的存成自己的配方。',
        ['Only this']                  = '只用这个',
        ['+ Save ticked passives as recipe'] = '+ 把已勾选的被动存为配方',
        ['None of these passives are in this game build.'] = '这个版本的游戏里没有这些被动。',
        ['Stratagems'] = '战备',
        ['Hellpod loadout'] = '空降舱配装',
        ['Stratagem presets'] = '战备预设',
        ['Your stratagem presets'] = '我的战备预设',
        ['None yet. Pick four stratagems, then save them.'] = '还没有。选好四个战备后保存。',
        ['+ Save current loadout'] = '+ 保存当前配装',
        ['On the loadout screen now'] = '配装界面当前',
        ['Apply to loadout'] = '应用到配装',
        ['Only stratagems you have unlocked are put in. Not while you are ready.'] = '只会放入你已解锁的战备。准备状态下无效。',
        ['Pick four stratagems on the loadout screen, then "+ Save current loadout". Click a saved one to put it back.'] = '在配装界面选好四个战备，然后点「+ 保存当前配装」。点已保存的可以放回去。',
        ['Finding the game\'s loadout code...'] = '正在查找游戏的配装代码...',
        ['Open the Hellpod loadout screen (before a mission).'] = '请打开空降舱配装界面（任务开始前）。',
        ['Armor weight']               = '护甲重量',
        ["An armor's weight class sets its speed, stamina regen and base armor rating. Pick one and the armor keeps its look."]
                                       = '护甲的重量等级决定移动速度、耐力回复与基础护甲值。选一个，护甲外观不变。',
        ['Game']                       = '游戏原值',
        ['Light']                      = '轻型',
        ['Medium']                     = '中型',
        ['Heavy']                      = '重型',
        ['As above']                   = '同上',
        ['What each weight gives (game values)'] = '各重量档的游戏数值',
        ['Game keyboard and mouse while open'] = '面板打开时的游戏键鼠',
        ['The game gets no keyboard or mouse while the panel is open'] = '面板打开时游戏收不到键盘和鼠标',
        ['The game gets your keyboard and mouse while the panel is open'] = '面板打开时游戏收得到键盘和鼠标',
        ['Blocked']                    = '拦截',
        ['Let through']                = '放行',
        ['Mascot']                     = '吉祥物',
        ['On']                         = '开',
        ['Off']                        = '关',
        ['Panel size (CTRL 0 resets size and position)'] = '面板尺寸（CTRL 0 重置大小与位置）',
        ['Search passives and effects'] = '搜索被动与效果',
        ['Open / close the panel']     = '打开 / 关闭面板',
        ['Swap to the next preset (panel closed)'] = '切换到下一个预设（面板关闭时）',
        ['Quick-swap key: off']        = '快速切换键：关',
        ['Set / cancel a typed value'] = '确认 / 取消输入的数值',
        ['Tabs, names, ticks and buttons'] = '标签页、名称、勾选与按钮',
        ['Scroll the list under the cursor'] = '滚动光标下的列表',
        ['The top strip moves the panel'] = '拖动顶部条移动面板',
        ['Move between controls']      = '在控件之间移动',
        ['Back / close']               = '返回 / 关闭',
        ['Tick the chosen passive']    = '勾选选中的被动',
        ['Scroll']                     = '滚动',
        ['Something wrong?']           = '遇到问题？',
        ['Copy a report and paste it in your bug report on the mod page.'] = '复制报告，粘贴到模组页面的 bug 反馈里。',
        ['Copy problem report']        = '复制问题报告',
        ['Problem report copied: paste it in your bug report'] = '问题报告已复制：粘贴到你的 bug 反馈里',
        ['While the panel is open the game ignores your keyboard and mouse (Keys tab: Blocked / Let through). Something wrong? Keys tab, Copy problem report.']
                                       = '面板打开时游戏会忽略你的键盘和鼠标（按键页：拦截 / 放行）。遇到问题？用按键页的「复制问题报告」。',
        ['Wear the armor you want to boost. The panel opens on its passive\'s tab, and the box at the top shows what you\'re wearing.']
                                       = '穿上想强化的护甲。面板会打开它的被动标签页，顶部的框显示你正穿的护甲。',
        ['Wear the armor you want to change. The panel opens on its passive\'s tab, and the box at the top shows what you\'re wearing.']
                                       = '穿上想改动的护甲。面板会打开它的被动标签页，顶部的框显示你正穿的护甲。',
        ['No tab for it yet? Click that box, or + Armor and pick the passive of the armor you wear.']
                                       = '还没有它的标签页？点击那个框，或用「+ 护甲」选你护甲的被动。',
        ['On its tab, choose the passive it should have instead. Original puts the game\'s own back.']
                                       = '在它的标签页里选择要换成哪个被动。「原始」恢复游戏自带被动。',
        ['It applies at once. Re-select the armor in the armory if the card still shows the old passive.']
                                       = '立即生效。如果卡片还显示旧被动，去军械里重新选中这件护甲。',
        ['Tick passives on the left: they stack onto every armor with that tab\'s passive.']
                                       = '勾选左边的被动：会叠加到所有带该标签页被动的护甲上。',
        ['Click a passive\'s name to see its values on the right; -- - + ++ change them, or click a value and type one.']
                                       = '点击被动名称在右侧查看数值；-- - + ++ 改动数值，或点数值直接输入。',
        ['Armor weight: make that passive\'s armors light, medium or heavy, or only the armor you\'re wearing.']
                                       = '护甲重量：让该被动的护甲变轻型、中型或重型，或只改你正穿的那件。',
        ['Copy code / Paste code share a loadout with a friend.'] = '复制代码 / 粘贴代码可以把配装分享给朋友。',
        ['Copy code / Paste code share a loadout (the web builder reads them too).'] = '复制代码 / 粘贴代码分享配装（网页版生成器也认）。',
        ['Presets: save loadouts, then the quick-swap key swaps between them without opening the panel.']
                                       = '预设：保存配装后，按快速切换键即可在不开面板的情况下切换。',
        ['Changes apply at once and are saved when you close the panel. Solo and private lobbies only.']
                                       = '改动即时生效，关闭面板时自动保存。仅限单人 / 私人房间。',
    },

    -- ---------------------------------------------------------------- 2. 带数字的句子
    -- { Lua pattern, 替换 }；^...$ 锚定整句。面板会把标签转成大写，所以同一句会同时
    -- 登记原文和全大写两份。
    pat = {
        -- 6.2.1: Every armor
        { '^(.+)  %-  ANY ARMOR YOU WEAR$',                  '%1  -  你穿的任何护甲' },
        { '^(.+)  %-  YOUR ARMOR$',                          '%1  -  你的护甲' },
        { "^ARMOR'S OWN PASSIVE: KEEP$",                     '护甲自带被动：保留' },
        { "^ARMOR'S OWN PASSIVE: OFF$",                      '护甲自带被动：关闭' },
        { '^This stack goes on every armor whose passive has no tab of its own %((%d+) passive%(s%) now%)%. Change armor as often as you like: the stack and its weight stay%.$',
          '这套堆叠会加到所有被动没有自己标签页的护甲上（当前 %1 个被动）。随便换护甲：堆叠和重量都不变。' },
        { '^Applies to all (%d+) armor%(s%) with no tab of their own%. Passives on the armor add to it %(e%.g%. Extra Padding %+50 armor%)%.$',
          '对所有 %1 件没有自己标签页的护甲生效。护甲上的被动会额外加成（例如额外垫料 +50 护甲值）。' },
        { '^(%d+) passive%(s%) stacked on (%d+) armor passive%(s%) without their own tab, own passives off$',
          '已堆叠 %1 个被动，作用于 %2 个没有自己标签页的护甲被动，自带被动已关闭' },
        { '^(%d+) passive%(s%) stacked on (%d+) armor passive%(s%) without their own tab$',
          '已堆叠 %1 个被动，作用于 %2 个没有自己标签页的护甲被动' },
        { '^(.+): Every armor stack, (%d+) passive%(s%), own passive off %(tab (%d+)%)$', '%1：所有护甲堆叠，%2 个被动，自带被动已关闭（标签页 %3）' },
        { '^(.+): Every armor stack, (%d+) passive%(s%), own passive off$', '%1：所有护甲堆叠，%2 个被动，自带被动已关闭' },
        { '^(.+): Every armor stack, (%d+) passive%(s%) %(tab (%d+)%)$', '%1：所有护甲堆叠，%2 个被动（标签页 %3）' },
        { '^(.+): Every armor stack, (%d+) passive%(s%)$',   '%1：所有护甲堆叠，%2 个被动' },
        -- 6.2 (added with the port; Armory Forge's own wording, not hd2modpj's)
        { '^(.+): (%d+) passive%(s%) stacked %(tab (%d+)%)$', '%1：%2 个被动已堆叠（标签页 %3）' },
        { '^(.+): tab (%d+), nothing ticked yet %(tab (%d+)%)$', '%1：标签页 %2，还没有勾选' },
        { '^GAME VALUE (.+)$',                               '游戏原值 %1' },
        { '^Armor (0x%x+)$',                                 '护甲 %1' },
        { '^Applies to: (.+)$',                              '适用于：%1' },
        { '^(.+) in game cycles your loadouts %(or the standard ones%)%.$',
          '在游戏中按 %1 循环切换配装（没有自己的就用标准配发）。' },
        { "^(%d+) ON$",                                  '%1 项已开启' },
        { "^(%d+) PASSIVES$",                           '%1 个被动' },
        { "^(%d+) PASSIVES  YOURS$",                    '%1 个被动  我的' },
        { "^(%d+) SAVED$",                               '已保存 %1 个' },
        { "^Armor stack (%d+) / (%d+)$",                 '护甲堆叠 %1 / %2' },
        { "^Undo %((%d+)%)$",                            '撤销（%1）' },
        { "^Reset (.+)$",                                '重置 %1' },
        { "^On (.+) armor%.$",                           '在%1护甲上生效。' },
        { "^(.+) armor$",                                '%1 护甲' },
        { "^Panel size (%d+)%%$",                        '面板尺寸 %1%%' },
        { "^Press (.+) to forge your armor$",            '按 %1 打造你的护甲' },
        { "^your preset (%d+) of (%d+)$",                '我的预设 %1 / %2' },
        { "^preset (%d+) of (%d+)$",                     '预设 %1 / %2' },
        { "^ARMORY FORGE  %-  (.+)$",                    '军械工坊 - %1' },
        { "^Added a stack for (.+) armor$",              '已为%1护甲添加一套堆叠' },
        { "^Removed the (.+) stack %(the game's own values are back%)$",
          '已移除%1堆叠（游戏原始数值已恢复）' },
        { "^Loaded the pasted code: (.+)$",              '已载入粘贴的代码：%1' },
        { '^Saved as "(.+)"$',                           '已保存为「%1」' },
        { "^Undone %((%d+) more%)$",                     '已撤销（还能撤销 %1 步）' },
        { "^Not a number: (.+)$",                        '这不是数字：%1' },
        { '^Deleted "(.+)"$',                            '已删除「%1」' },
        { '^Saved your current stacks into "(.+)"$',     '已把当前堆叠存入「%1」' },
        { '^Saved%. Type a name for it, or press Enter to keep "(.+)"%.$',
          '已保存。输入名称，或按回车保留「%1」。' },
        { "^GAME VALUE (%S+)%s+WAS (%S+)$",              '游戏原值 %1 原为 %2' },
        { "^Reading the game's armor passives%.%.%. %((%d+) of (%d+) found%)$",
          '正在读取游戏的护甲被动...（已找到 %1/%2）' },
        { "^(%d+) passive%(s%) stacked, %+(%d+) row%(s%) in the game's data %- (%d+) overlap%(s%)$",
          '已堆叠 %1 个被动，游戏数据中新增 %2 行 - %3 处重叠' },
        { "^(%d+) passive%(s%) stacked, %+(%d+) row%(s%) in the game's data$",
          '已堆叠 %1 个被动，游戏数据中新增 %2 行' },
        { "^(%d+) passive%(s%), (%d+) value%(s%) changed, (.+)$",
          '%1 个被动、%2 项数值已改动，%3' },
        { "^(.+) in game cycles your loadouts %(or the standard ones%)$",
          '在游戏中按 %1 循环切换配装（没有自己的就用标准配发）' },
        -- ---- 5.4/5.5 新增句式
        { "^The panel now opens with (.+)$",             '面板打开键已改为 %1' },
        { "^Quick%-swap is now (.+)$",                   '快速切换键已改为 %1' },
        { '^Size: (%d+)%%  %(Ctrl %+ / Ctrl %-, or %[%-] %[%+%] at the top%)$',
          '尺寸：%1%%（Ctrl + / Ctrl - 或顶部的 [-] [+]）' },
        { '^Nothing matches "(.+)"%.$',                  '没有匹配「%1」的结果' },
        { '^%+(%d+) more$',                              '还有 %1 件' },
        { '^Everything on this armor together: its own passive plus (%d+) stacked%. An estimate: how the game combines stacked values is not confirmed yet%.$',
          '这件护甲的效果全部合计：自带被动加叠加的 %1 个被动。这是估算值：游戏合并叠加数值的方式尚未确认。' },
        { '^Added (.+) armor$',                          '已添加%1护甲' },
        { '^Armor (%d+) / (%d+)$',                       '护甲 %1 / %2' },
        { '^Every (.+) armor has (.+) instead of its own passive%.$',
          '%1护甲现在拥有%2，而非自带被动。' },
        { "^Waiting for (.+) in the game's data%.%.%.$", '正在等待游戏数据中的%1……' },
        { '^Active: (.+) armor has (.+)$',               '已生效：%1护甲当前为%2' },
        { '^(.+) armor now has (.+)$',                   '%1护甲现在换成了%2' },
        { "^(.+) armor has its own passive again$",      '%1护甲已恢复自带被动' },
        { '^Original: (.+)$',                            '原始：%1' },
        { '^has (.+)$',                                  '拥有%1' },
        -- ---- 5.6/5.7/6.0/6.1 新增句式（%1 里的护甲名、被动名会被片段替换二次处理）
        { "^Presets: save loadouts, then (.+) swaps between them without opening the panel%.$",
          '预设：保存配装后，按 %1 即可在不开面板的情况下切换。' },
        { '^(.+): no swap yet%. Click to add its tab$',      '%1：还没有换装。点击添加它的标签页' },
        { '^(.+): nothing stacked%. Click to add its tab$',  '%1：还没有堆叠。点击添加它的标签页' },
        { '^(.+): keeps its own passive$',                   '%1：保留自带被动' },
        { '^(.+): keeps its own passive %(tab (%d+)%)$',     '%1：保留自带被动（标签页 %2）' },
        { '^(.+) %-> (.+) %(tab (%d+)%)$',                   '%1 → %2（标签页 %3）' },
        { '^(.+) %-> (.+)$',                                 '%1 → %2' },
        { '^(.+): (%d+) passive%(s%) stacked$',              '%1：%2 个被动已堆叠' },
        { '^(.+): tab (%d+), nothing ticked yet$',           '%1：标签页 %2，还没有勾选' },
        { '^ARMOR WEIGHT: GAME$',                            '护甲重量：游戏原值' },
        { '^ARMOR WEIGHT: LIGHT$',                           '护甲重量：轻型' },
        { '^ARMOR WEIGHT: MEDIUM$',                          '护甲重量：中型' },
        { '^ARMOR WEIGHT: HEAVY$',                           '护甲重量：重型' },
        { '^ARMOR (.+)    SPEED (.+)    STAMINA REGEN (.+)$', '护甲 %1    速度 %2    耐力回复 %3' },
        { '^Applies to all (%d+) armor%(s%) with (.+)%. Passives on the armor add to it %(e%.g%. Extra Padding %+50 armor%)%.$',
          '对拥有 %2 的全部 %1 件护甲生效。护甲上的被动会额外加成（例如额外垫料 +50 护甲值）。' },
        { "^The armor records for (.+) were not found yet, so the weight can't apply%. Load into your ship or a mission%.$",
          '%1 的护甲记录还没找到，重量无法生效。请进入飞船或任务。' },
        { '^WEAR ANY OF: (.+)$',                             '可穿戴：%1' },
        { "^Only the armor you're wearing: (.+)$",           '仅限你正穿的护甲：%1' },
        { '^(.+): light weight$',                            '%1：轻型' },
        { '^(.+): medium weight$',                           '%1：中型' },
        { '^(.+): heavy weight$',                            '%1：重型' },
        { '^(.+): same as its passive$',                     '%1：与其被动一致' },
        { '^(.+) armors: light weight$',                     '%1护甲：轻型' },
        { '^(.+) armors: medium weight$',                    '%1护甲：中型' },
        { '^(.+) armors: heavy weight$',                     '%1护甲：重型' },
        { '^(.+) armors: their own weight$',                 '%1护甲：各自原重量' },
        { '^Added (.+) %(your armor%)$',                     '已添加%1（你的护甲）' },
    },

    -- ---------------------------------------------------------------- 3. 通用词黑名单
    -- Close / Undo / Delete 这类单词别的模组（菜单、按键提示）也很可能画同样的字。
    -- 它们是整串精确匹配，所以命中时会一起被翻译；把 on.generic 设成 false 就能整批
    -- 跳过，把误伤压到几乎为零 —— Armory Forge 自己的长句、名称不受任何影响。

    -- ---------------------------------------------------------------- 4. 片段替换（白名单）
    -- 只有登记在这里的才会在句子**内部**替换；上面 ui / effect 表里的词一律只做
    -- 整串精确匹配，不会去动句子里的单词。
    -- 护甲被动名与预设名是游戏专有名词，也允许进句子里替换（"Reset Med-Kit" ->
    -- "重置 医疗包"），但太短的、或本身就是常见英文单词的走下面 no_frag 例外。
    no_frag = { scout = true, tank = true, stealth = true, gunner = true, survivor = true },
    -- the end of a string translated on its own, the rest looked up again
    suffix = {
        { ' (name is a guess)', '（名称为推测）' },
    },
    frag = {
        { ', stack all',        '，全部叠加',    'ui' },
        { ', strongest only',   '，仅取最强',    'ui' },
        { ',stack all',         '，全部叠加',    'ui' },
        { '，stack all',        '，全部叠加',    'ui' },
        { '，strongest only',   '，仅取最强',    'ui' },
        { ' armor',             ' 护甲',         'ui' },
        { ' (name is a guess)', '（名称为推测）', 'ui' },
        { '(weapon stat)',      '（武器属性）',  'effect' },
    },

    -- ---------------------------------------------------------------- 5. 护甲被动名
    perk = {
        ['Extra Padding']                      = '额外垫料',
        ['Scout']                              = '侦察',
        ['Fortified']                          = '强化',
        ['Electrical Conduit']                 = '电路导管',
        ['Engineering Kit']                    = '工程包',
        ['Med-Kit']                            = '医疗包',
        ['Servo-Assisted']                     = '伺服辅助',
        ['Democracy Protects']                 = '民主护佑',
        ['Reinforced Epaulettes']              = '强化肩章',
        ['Inflammable']                        = '易燃',
        ['Peak Physique']                      = '健壮体格',
        ['Advanced Filtration']                = '高级过滤能力',
        ['Unflinching']                        = '毫不畏缩',
        ['Acclimated']                         = '应变自如',
        ['Siege-Ready']                        = '蓄势出击',
        ['Integrated Explosives']              = '集成炸药',
        ['Gunslinger']                         = '神枪手',
        ['Adreno-Defibrillator']               = '肾上腺素除颤器',
        ['Ballistic Padding']                  = '防弹内衬',
        ['Desert Stormer']                     = '沙漠突击者',
        ['Feet First']                         = '护腿为上',
        ['Reduced Signature']                  = '隐迹潜踪',
        ['Rock-Solid']                         = '坚如磐石',
        ['Supplemental Adrenaline']            = '肾上腺素补充剂',
        ['Concussive Padding, Reinforced']     = '防震内衬(强化型)',
        ['Concussive Padding, Grenadier']      = '防震内衬(掷弹兵型)',
        ['Concussive Padding, Hazmat']         = '防震内衬(防化型)',
        ['Oxygenator']                         = '供氧器',
        ['Kinetic Displacement Mitigation']    = '动能位移减缓',
        ['Blunt-Force Mitigation']             = '钝击创伤缓和',
        ['True Grit']                          = '坚韧不拔',
        ['Standard Issue']                     = '标准配发',
        ['Every armor']                        = '所有护甲',
    },

    -- ---------------------------------------------------------------- 6. 效果名
    -- 面板显示的是 label_of(e)：把 key 的下划线换成空格、首字母大写；武器属性类会
    -- 再带上 "(weapon stat)"。这里照着显示出来的样子登记。
    effect = {
        ['Armor rating']               = '护甲值',
        ['Radar ping']                 = '雷达扫描间隔',
        ['Detection radius']           = '敌人探测半径',
        ['Crouch prone recoil']        = '蹲伏/匍匐时后坐力',
        ['Explosive damage taken']     = '爆炸伤害抗性',
        ['Arc damage taken']           = '电弧伤害抗性',
        ['Arc secondary']              = '电弧传递[不明]',
        ['Throwables']                 = '额外投掷物数量',
        ['Stims']                      = '额外治疗针数量',
        ['Stim duration']              = '治疗针持续时间',
        ['Throw range']                = '投掷距离',
        ['Limb health']                = '四肢生命值',
        ['Death save']                 = '免死几率',
        ['Chest bleed']                = '胸部出血时受到其他出血伤害比例',
        ['Primary reload speed']       = '主武器装填速度',
        ['Limb injury avoid']          = '四肢受伤免疫',
        ['Melee damage']               = '近战伤害',
        ['Fire damage taken']          = '火焰伤害抗性',
        ['Ergonomics']                 = '人机工效',
        ['Melee flag']                 = '近战标记[注:效果不明]',
        ['Gas damage taken']           = '毒气伤害抗性',
        ['Flinch']                     = '畏缩反应',
        ['Elemental damage taken']     = '火毒酸电伤害抗性',
        ['Ammo capacity']              = '弹药容量',
        ['Death explosion delay']      = '死亡后爆炸延迟',
        ['Sidearm reload speed']       = '副武器装填速度',
        ['Sidearm draw speed']         = '副武器切换速度',
        ['Sidearm recoil']             = '副武器后坐力',
        ['Revive marker']              = '短暂复活',
        ['Chest damage taken']         = '胸部伤害抗性',
        ['Movement noise']             = '移动时噪音',
        ['Poi range']                  = '探索点[注:兴趣点]显示距离',
        ['Leg injury immunity']        = '腿伤免疫',
        ['Stagger']                    = '被击倒概率',
        ['Stamina on damage']          = '受伤时恢复耐力',
        ['Impact damage taken']        = '撞击伤害承受',
        ['Move speed a']               = '移动速度 A',
        ['Move speed b']               = '移动速度 B',
        ['Slide flag']                 = '滑铲标记[不明]',
        ['Support reload speed']       = '支援武器装填速度',
        -- 武器属性（stat）类：面板显示的是 label_of(e)，它先去掉 key 的 stat_ 前缀、
        -- 再把下划线换成空格、首字母大写，最后拼上 " (weapon stat)"。所以这里登记的
        -- 是最终那一整串（stat_flinch -> "Flinch (weapon stat)"）。
        ['Flinch (weapon stat)']          = '受击抖动（武器属性）',
        ['Ammo capacity (weapon stat)']   = '弹药容量（武器属性）',
        ['Primary reload (weapon stat)']  = '主武器装填速度（武器属性）',
        ['Support reload (weapon stat)']  = '支援武器装填速度（武器属性）',
        ['Sidearm reload (weapon stat)']  = '副武器装填速度（武器属性）',
        ['Sidearm draw (weapon stat)']    = '副武器切换速度（武器属性）',
        ['Sidearm recoil (weapon stat)']  = '副武器后坐力（武器属性）',
    },

    -- ---------------------------------------------------------------- 7. 数值单位说明
    unit = {
        ['damage resist (100% = none taken)'] = '伤害减免（100% = 完全不受伤）',
        ['change from normal']                = '相对原版的增减',
        ['armor rating']                      = '护甲值',
        ['extra']                             = '额外数量',
        ['seconds']                           = '秒',
        ['value (flag)']                      = '数值（开关）',
    },

    -- ---------------------------------------------------------------- 8. 内置预设名
    preset = {
        ['Kitchen Sink']   = '万金油',
        ['Tank']           = '重装坦克',
        ['Stealth']        = '潜行',
        ['Survivor']       = '生存者',
        ['Demolitionist']  = '爆破手',
        ['Gunner']         = '枪手',
        ['My preset']      = '我的预设',
    },

    -- ---------------------------------------------------------------- 9. 被动说明（5.5 新增）
    -- 来源 tools/passives.json，经 picker.py 生成为面板里的 local PASSIVE_INFO —— 外挂
    -- 拿不到那个表的引用，只能在画出来时整句拦。好在说明都单行绘制（wrap() 按宽度断行，
    -- 这些长度在 720p~4K 都一行放得下），整串精确匹配可靠；万一将来断行，就整条退回英文。
    desc = {
        ['50% fire, gas, acid and arc resist.'] = '50% 火焰、毒气、酸液与电弧抗性。',
        ['One short revive after a death (body intact); stims last 2 s longer; 50% arc resist.'] = '死亡后可短暂复活一次（遗体完整）；治疗针持续时间延长 2 秒；50% 电弧抗性。',
        ['80% gas resist.'] = '80% 毒气抗性。',
        ['25% chest and 25% explosive resist; no chest bleeding.'] = '25% 胸部抗性与 25% 爆炸抗性；不会胸部出血。',
        ['Harder to knock down; 30% impact resist; higher armor rating.'] = '更难被击倒；30% 撞击抗性；护甲值更高。',
        ['50% explosive resist; +2 grenades.'] = '50% 爆炸抗性；+2 手雷。',
        ['50% explosive resist; 25% gas resist; 30% less sidearm recoil.'] = '50% 爆炸抗性；25% 毒气抗性；副武器后坐力降低 30%。',
        ['50% explosive resist; higher armor rating.'] = '50% 爆炸抗性；护甲值更高。',
        ['50% chance to survive a lethal hit; no chest bleeding.'] = '50% 几率在致命一击后存活；不会胸部出血。',
        ['40% fire, gas, acid and arc resist; +20% throw range.'] = '40% 火焰、毒气、酸液与电弧抗性；+20% 投掷距离。',
        ['95% arc resist.'] = '95% 电弧抗性。',
        ['30% less recoil crouched or prone; +2 grenades.'] = '蹲伏或匍匐时后坐力降低 30%；+2 手雷。',
        ['Higher armor rating.'] = '护甲值更高。',
        ['50% quieter movement; +30% point-of-interest range; no leg injuries.'] = '移动更安静 50%；+30% 兴趣点显示范围；腿部不会受伤。',
        ['30% less recoil crouched or prone; 50% explosive resist.'] = '蹲伏或匍匐时后坐力降低 30%；50% 爆炸抗性。',
        ['Sidearms: +40% reload speed, +50% draw speed, 70% less recoil.'] = '副武器：+40% 装填速度、+50% 切换速度、后坐力降低 70%。',
        ['75% fire resist.'] = '75% 火焰抗性。',
        ['Armor explodes 1.5 s after you die; +2 grenades.'] = '护甲在你死亡 1.5 秒后爆炸；+2 手雷。',
        ['50% fire resist; 50% chance to avoid limb injury; 30% impact resist.'] = '50% 火焰抗性；50% 几率避免四肢受伤；30% 撞击抗性。',
        ['+2 stims; stims last 2 s longer.'] = '+2 治疗针；治疗针持续时间延长 2 秒。',
        ['Faster walking and running; faster, longer slides.'] = '步行与奔跑更快；滑铲更快、更远。',
        ['+40% melee damage; better weapon handling.'] = '+40% 近战伤害；武器操控更佳。',
        ['50% quieter movement; enemies spot you from 40% closer.'] = '移动更安静 50%；敌人发现你的距离缩短 40%。',
        ['+30% primary reload; 50% chance to avoid limb injury; +20% melee damage.'] = '+30% 主武器装填；50% 几率避免四肢受伤；+20% 近战伤害。',
        ['+40% melee damage; harder to knock down.'] = '+40% 近战伤害；更难被击倒。',
        ['Map markers scan for enemies every 2 s; enemies spot you from 30% closer.'] = '地图标记每 2 秒扫描一次敌人；敌人发现你的距离缩短 30%。',
        ['+30% throw range; +50% limb health.'] = '+30% 投掷距离；+50% 四肢生命值。',
        ['+30% primary reload; +20% ammo for all weapons (not backpacks).'] = '+30% 主武器装填；所有武器（背包武器除外）+20% 弹药。',
        ['Taking damage restores stamina; higher armor rating.'] = '受伤时恢复耐力；护甲值更高。',
        ['+30% support weapon reload; better weapon handling.'] = '+30% 支援武器装填；武器操控更佳。',
        ['Less flinch when hit; higher armor rating; map markers scan every 2 s.'] = '受击时畏缩减轻；护甲值更高；地图标记每 2 秒扫描一次。',
    },

    -- ---------------------------------------------------------------- 10. 护甲名（6.0 新增）
    -- 来源 tools/armor-names.json（FileDiver dump，411 套 / 222 个名字），全部取游戏官方
    -- 简体译名（schinese.txt 按英文原文反查）；"9a7c0da" 是 dump 噪音不收。官方弯引号
    -- “ ” 一律换成 ASCII 双引号（字形保险）。同名护甲/头盔/披风共用一条翻译。
    armor = {
        ['A-35 Recon'] = 'A-35"侦察者"',
        ['A-9 Helljumper'] = 'A-9"地狱伞兵"',
        ['AC-1 Dutiful'] = 'AC-1"恪尽职守"',
        ['AC-2 Obedient'] = 'AC-2"服从指挥"',
        ['AD-11 Livewire'] = 'AD-11"生龙活虎"',
        ['AD-26 Bleeding Edge'] = 'AD-26"血刃科技"',
        ['AD-49 Apollonian'] = 'AD-49"阿波罗神"',
        ['AF-02 Haz-Master'] = 'AF-02"危害大师"',
        ['AF-50 Noxious Ranger'] = 'AF-50"毒瘴游骑兵"',
        ['AF-52 Lockdown'] = 'AF-52"禁锢"',
        ['AF-91 Field Chemist'] = 'AF-91"实地化学家"',
        ['Against the Tyrant Cloud'] = '破除暴瘴',
        ['Agent of Oblivion'] = '湮灭使者',
        ['B-01 Tactical'] = 'B-01"战术"',
        ['B-02 Gloom Warden'] = 'B-02阴霾守望者',
        ['B-08 Light Gunner'] = 'B-08"轻装枪手"',
        ['B-16 Battle-Scarred Veteran'] = 'B-16"百战老兵"',
        ['B-22 Model Citizen'] = 'B-22"模范公民"',
        ['B-24 Enforcer'] = 'B-24"执行者"',
        ['B-27 Fortified Commando'] = 'B-27"强化突击兵"',
        ['BFM-16 Tanker'] = 'BFM-16"坦克手"',
        ['BFM-220 Ironclad'] = 'BFM-220"铁甲"',
        ['BFM-77 Reformer'] = 'BFM-77"改良者"',
        ['BP-20 Correct Officer'] = 'BP-20"思想矫正官"',
        ['BP-32 Jackboot'] = 'BP-32"杰克军靴"',
        ['BP-77 Grand Juror'] = 'BP-77"大陪审员"',
        ['Badge of Order'] = '秩序徽章',
        ['Bastion of Integrity'] = '忠义堡垒',
        ['Beacon of Mercy'] = '仁慈信标',
        ['Blazing Samaritan'] = '慈心闪耀',
        ['Botslayer'] = '机械屠戮者',
        ['Bugslayer'] = '诛虫煞星',
        ['CE-07 Demolition Specialist'] = 'CE-07"拆除专家"',
        ['CE-101 Guerilla Gorilla'] = 'CE-101 "游击猩猩"',
        ['CE-27 Ground Breaker'] = 'CE-27"裂地者"',
        ['CE-35 Trench Engineer'] = 'CE-35"战壕工程师"',
        ['CE-64 Grenadier'] = 'CE-64"掷弹兵"',
        ['CE-67 Titan'] = 'CE-67"泰坦"',
        ['CE-74 Breaker'] = 'CE-74"破裂者"',
        ['CE-81 Juggernaut'] = 'CE-81"巨人"',
        ['CM-09 Bonesnapper'] = 'CM-09"碎骨杀手"',
        ['CM-10 Clinician'] = 'CM-10"临床医师"',
        ['CM-14 Physician'] = 'CM-14"医师"',
        ['CM-17 Butcher'] = 'CM-17"屠夫"',
        ['CM-21 Trench Paramedic'] = 'CM-21"战壕护理员"',
        ['CPG-48 Sapper'] = 'CPG-48"工兵"',
        ['CPH-26 Commandant'] = 'CPH-26"司令官"',
        ['CPR-80 Bulwark'] = 'CPR-80 "壁垒"',
        ['CW-22 Kodiak'] = 'CW-22"科迪亚克"',
        ['CW-36 Winter Warrior'] = 'CW-36"冬日战兵"',
        ['CW-4 Arctic Ranger'] = 'CW-4"极地游骑兵"',
        ['CW-9 White Wolf'] = 'CW-9"白狼"',
        ['Camo Cloak'] = '迷彩斗篷',
        ['City Fighter\'s Resolve'] = '城市战士的决意',
        ['Cloak of Posterity\'s Gratitude'] = '后族怀恩披风',
        ['Conductor of Brilliance'] = '辉煌指挥官',
        ['Cover of Darkness'] = '黑夜守护',
        ['Crest of the Unsullied'] = '无垢徽章',
        ['Cresting Honor'] = '荣誉之巅',
        ['DP-00 Tactical'] = 'DP-00"战术"',
        ['DP-11 Champion of the People'] = 'DP-11"人民捍卫者"',
        ['DP-40 Hero of the Federation'] = 'DP-40"联邦英雄"',
        ['DP-53 Savior of the Free'] = 'DP-53"自由救星"',
        ['DP-8 Mountain-Scaled'] = 'DP-8"山峦鳞甲"',
        ['DS-10 Big Game Hunter'] = 'DS-10"巨兽猎手"',
        ['DS-191 Scorpion'] = 'DS-191"天蝎"',
        ['DS-42 Federation\'s Blade'] = 'DS-42"联邦之刃"',
        ['De-Forester\'s Sailcloth'] = '伐木工帆布',
        ['Defender of Our Dream'] = '梦想卫士',
        ['Defender of the Wall'] = '高墙捍卫者',
        ['Diagram of the Noblest Payload'] = '至高使命图谱',
        ['Dignity of Toil'] = '劳作的荣光',
        ['Dissident\'s Nightmare'] = '异见者梦魇',
        ['Drape of Glory'] = '荣光加身',
        ['EX-00 Prototype X'] = 'EX-00"原型X"',
        ['EX-03 Prototype 3'] = 'EX-03"原型 3"',
        ['EX-16 Prototype 16'] = 'EX-16"原型 16"',
        ['Eagle\'s Fury'] = '飞鹰之怒',
        ['Emblem of Freedom'] = '自由象征',
        ['Eternal Corona'] = '永恒日冕',
        ['Executioner\'s Canopy'] = '刽子手的披风',
        ['Eye of Freedom'] = '自由之眼',
        ['Eye of Liberty'] = '解放之眼',
        ['Eye of the Clandestine'] = '隐匿之眼',
        ['FS-05 Marksman'] = 'FS-05"神射手"',
        ['FS-11 Executioner'] = 'FS-11"行刑者"',
        ['FS-23 Battle Master'] = 'FS-23"战斗大师"',
        ['FS-34 Exterminator'] = 'FS-34"灭绝者"',
        ['FS-37 Ravager'] = 'FS-37"破坏者"',
        ['FS-38 Eradicator'] = 'FS-38"根除者"',
        ['FS-55 Devastator'] = 'FS-55"蹂躏者"',
        ['FS-61 Dreadnought'] = 'FS-61"无畏"',
        ['Fallen Hero\'s Vengeance'] = '陨落英雄之崛起',
        ['Federation\'s Embrace'] = '联邦怀抱',
        ['Foe Rent Asunder'] = '敌分四裂',
        ['Foesmasher'] = '歼敌战士',
        ['Fre Liberam'] = '求自由',
        ['Free-Spirited Spangles'] = '自由之魂的辉映',
        ['Freedom\'s Tapestry'] = '自由织锦',
        ['GS-11 Democracy\'s Deputy'] = 'GS-11"民主代理人"',
        ['GS-17 Frontier Marshal'] = 'GS-17"边境元帅"',
        ['GS-66 Lawmaker'] = 'GS-66"立法者"',
        ['Gilded Quill'] = '镀金羽毛笔',
        ['Greatcloak of Rebar Resolve'] = '钢筋意志大氅',
        ['Harbinger of True Equality'] = '真正的平等先锋',
        ['Holder of the Yellow Line'] = '黄线捍卫者',
        ['Honored Heirloom'] = '荣耀传家宝',
        ['Humble Regalia'] = '谦卑徽记',
        ['I-09 Heatseeker'] = 'I-09"热力追踪"',
        ['I-102 Draconaught'] = 'I-102"龙行者"',
        ['I-44 Salamander'] = 'I-44"火蜥"',
        ['I-92 Fire Fighter'] = 'I-92"消防队"',
        ['IE-12 Righteous'] = 'IE-12"义士"',
        ['IE-3 Martyr'] = 'IE-3"烈士"',
        ['IE-57 Hell-Bent'] = 'IE-57"奋不顾身"',
        ['Independence Bringer'] = '独立先驱',
        ['Infiltrator'] = '深入敌阵',
        ['Ingress-81'] = '进军-81',
        ['Ix-Voidwalker'] = 'IX-寂域行者',
        ['Judgment Day'] = '审判日',
        ['Justice For All'] = '全民正义',
        ['KDM-500 Outrider'] = 'KDM-500"先驱骑兵"',
        ['KDM-73 Dragoon'] = 'KDM-73"龙骑兵"',
        ['KDM-763 Pacesetter'] = 'KDM-763"领跑者"',
        ['Liberty\'s Herald'] = '解放预兆',
        ['Light of Eternal Liberty'] = '永恒自由之光',
        ['Mantle of True Citizenship'] = '忠诚公民之斗篷',
        ['Mark of the Constrictor'] = '缚暴印记',
        ['Mark of the Crimson Fang'] = '猩红獠牙之印',
        ['Martyris Rex'] = '殉道之王',
        ['Message of Morale'] = '士气宣言',
        ['Miranda\'s Legacy'] = '米兰达的遗志',
        ['Mother Eagle\'s Wings'] = '母鹰之翼',
        ['O-2 Heavy Operator'] = 'O-2"重装操作者"',
        ['O-3 Free Spirit'] = 'O-3"自由之魂"',
        ['O-44 Bonded Pilot'] = 'O-44"契约驾驶员"',
        ['Order of the Venerated Ballot'] = '神圣投票团',
        ['Over Artifice Triumphant'] = '巧取豪夺',
        ['PH-202 Twigsnapper'] = 'PH-202"折枝"',
        ['PH-56 Jaguar'] = 'PH-56"捷豹"',
        ['PH-9 Predator'] = 'PH-9"掠食者"',
        ['Patient Zero\'s Rememberance'] = '零号病人遗思',
        ['Patriot Blue'] = '爱国蓝',
        ['Per Democrasum'] = '于民主',
        ['Pillar of the Abyss'] = '深渊支柱',
        ['Pillars of Freedom'] = '自由支柱',
        ['Pinions of Everlasting Glory'] = '永恒荣耀之羽',
        ['Podium of Prosperity'] = '繁荣领奖台',
        ['Pride of the Whistleblower'] = '检举者的荣耀',
        ['Proof of Faultless Virtue'] = '无瑕德行之证',
        ['Prosperous Green'] = '繁荣绿',
        ['Protector of the Heart'] = '民主之心捍卫者',
        ['Proud Gold'] = '傲金',
        ['Purifying Eclipse'] = '净化日食',
        ['RE-1861 Parade Commander'] = 'RE-1861"阅兵指挥官"',
        ['RE-2310 Honorary Guard'] = 'RE-2310"荣誉卫队"',
        ['RE-824 Bearer of the Standard'] = 'RE-824 "执旗手"',
        ['RS-100 Sanctioner'] = 'RS-100"制裁者"',
        ['RS-20 Constrictor'] = 'RS-20"绞杀者"',
        ['RS-40 Beast of Prey'] = 'RS-40"掠食凶兽"',
        ['RS-6 Fiend Destroyer'] = 'RS-6"歼魔者"',
        ['RS-67 Null Cipher'] = 'RS-67"空密码"',
        ['RS-89 Shadow Paragon'] = 'RS-89"暗影典范"',
        ['Rags of the Fashionable'] = '时尚褴褛',
        ['Reaper of Bounties'] = '赏金收割者',
        ['Reckoning\'s Cheer'] = '清算颂歌',
        ['Red Planet\'s Memory'] = '红星回忆',
        ['Rightful Occupier'] = '正当占领者',
        ['SA-04 Combat Technician'] = 'SA-04"技术兵"',
        ['SA-12 Servo-Assisted'] = 'SA-12"伺服辅助"',
        ['SA-25 Steel Trooper'] = 'SA-25"钢铁士兵"',
        ['SA-32 Dynamo'] = 'SA-32"精力充沛"',
        ['SA-7 Headfirst'] = 'SA-7"冲锋者"',
        ['SA-8 Ram'] = 'SA-8"蛮悍"',
        ['SC-15 Drone Master'] = 'SC-15"无人机大师"',
        ['SC-30 Trailblazer Scout'] = 'SC-30"开路侦察兵"',
        ['SC-34 Infiltrator'] = 'SC-34"深入敌阵"',
        ['SC-37 Legionnaire'] = 'SC-37"军团士兵"',
        ['SR-18 Roadblock'] = 'SR-18"路障"',
        ['SR-24 Street Scout'] = 'SR-24"街头侦察兵"',
        ['SR-64 Cinderblock'] = 'SR-64"煤渣砖"',
        ['Schema Laid Bare'] = '解封蓝图',
        ['Scraps of Sovereignty'] = '主权碎片',
        ['Seal of General Consensus'] = '康森瑟斯将军之印',
        ['Shroud of the Juggernaut'] = '巨人披肩',
        ['Standard of Rapid Evacuation'] = '快速撤离披肩',
        ['Standard of Safe Distance'] = '安全距离标准',
        ['Stone-Wrought Perseverance'] = '磐石毅力',
        ['Strength in Our Arms'] = '武器之力',
        ['TG-122 Demo-Trooper'] = 'TG-122"爆破兵"',
        ['TG-8 Sharpshooter'] = 'TG-8"神枪手"',
        ['TR-117 Alpha Commander'] = 'TR-117"阿尔法指挥官"',
        ['TR-40 Gold Eagle'] = 'TR-40"金鹰"',
        ['TR-62 Knight'] = 'TR-62"骑士"',
        ['TR-7 Ambassador of the Brand'] = 'TR-7"形象大使"',
        ['TR-9 Cavalier of Democracy'] = 'TR-9"民主骑兵"',
        ['Testament to Attrition'] = '百战不殆的明证',
        ['The Breach'] = '突破',
        ['The Cape of Stars and Suffrage'] = '群星与选举之披肩',
        ['Thundering Hooves of Loyalty'] = '忠诚惊雷之蹄',
        ['Tideturner'] = '力挽狂澜',
        ['Tread of Liberty'] = '解放之履',
        ['Triangulation Veil'] = '三角定位披纱',
        ['Tyranny\'s Bane'] = '暴政的毁灭',
        ['Tyrant Hunter'] = '猎暴人',
        ['UF-16 Inspector'] = 'UF-16"督察员"',
        ['UF-50 Bloodhound'] = 'UF-50"猎犬"',
        ['UF-84 Doubt Killer'] = 'UF-84"疑虑克星"',
        ['Unblemished Allegiance'] = '无瑕忠诚',
        ['United in Equality'] = '仰齐与共',
        ['Vector of Victory'] = '胜利矢量',
        ['Veil of the Valorous Vagabond'] = '英勇游侠之披纱',
        ['Veridical Ideology'] = '真理意识形态',
        ['Veteran\'s Banner'] = '老兵旗帜',
        ['Vision of Freedom'] = '自由愿景',
        ['Watchful Compatriot'] = '守望同胞',
        ['Way of the Bandolier'] = '弹带之道',
        ['Wedgeful Tricorn'] = '楔形三角披肩',
        ['Will of the People'] = '人民的意志',
        ['Windswept Wayfinder'] = '风驰引路者',
        ['Wings of Valor'] = '勇气之翼',
    },

    -- ---------------------------------------------------------------- 缺字形替身
    -- 游戏的 UI 字体常常带汉字却不带全角标点（或反过来）。缺字形时引擎画 fallback 字形，
    -- 面板上就是一个 "?" —— 原本英文里的双引号被译成「」后就是这样掉的。这里登记它的
    -- ASCII 替身；探针量出某个字符没有字形时自动换掉，面板上就不会出现问号。
    fallback = {
        ['「'] = '"',  ['」'] = '"',
        ['（'] = '(',  ['）'] = ')',
        ['，'] = ',',  ['、'] = ',',
        ['。'] = '.',  ['：'] = ':',  ['；'] = ';',
        ['！'] = '!',  ['？'] = '?',
    },
}
