-- ================================================================ Japanese / 日本語
-- The panel's text in Japanese. Passive and armor names are the game's own Japanese text
-- (read from a game install with tools/armor-names/ and tools/armor_names.py --lang ja:
-- "アドレナリン除細動器", "AD-26 ブリーディング・エッジ"); the rest is translated for the panel
-- and uses the game's wording where it has one (ダメージ耐性, アーマー評価, 回復薬, 支援武器).
-- PP.tr in panel.lua looks things up here: ui / perk / effect / unit / preset / desc / armor
-- are whole strings (any case), pat are sentences with numbers or names in them, frag are
-- pieces replaced inside other text. fallback: ASCII stand-ins for punctuation the game
-- font has no glyph for. Missing strings simply stay English. The perk and armor
-- tables are generated (tools/lang_ja_gen.py); everything else is edited by hand.
local LANGS = LANGS or {}
LANGS.ja = {
    name = '日本語',
    credit = 'Armory Forge',
    ui = {
        -- 上部バー
        ['MINISTRY OF DEFENSE']        = '国防省',
        ['SUPER EARTH ARMORY FORGE']   = 'スーパーアース兵器工廠',
        ['SIZE']                       = 'サイズ',
        ['DRAG TO MOVE']               = 'ドラッグで移動',
        ['ARMORY']                     = '兵器庫',
        ['FORGE']                      = '鍛造',
        ['Tick passives, change values: it all applies at once.'] = 'パッシブを選んで数値を変えれば、すぐに反映されます。',
        -- 下部のキー表示
        ['Close']                      = '閉じる',
        ['Undo']                       = '元に戻す',
        ['Swap loadout']               = 'ロードアウト切替',
        ['SOLO / PRIVATE LOBBIES ONLY'] = 'ソロ / プライベートのみ',
        -- スキャン中
        ['Scanning armory records']    = '兵器庫の記録をスキャン中',
        ['Load into your ship or a mission if this does not finish.'] = '終わらない場合は、艦かミッションに入ってください。',
        -- タブ
        ['+ Armor']                    = '+ アーマー',
        ['Presets']                    = 'プリセット',
        ['REMOVE THIS STACK']          = 'このスタックを削除',
        ['CLICK AGAIN TO REMOVE']      = 'もう一度クリックで削除',
        -- プリセット画面
        ['Loadouts']                   = 'ロードアウト',
        ['Standard issue']             = '標準装備',
        ['Your loadouts']              = 'あなたのロードアウト',
        ['None yet. Save the current stack.'] = 'まだありません。現在のスタックを保存しましょう。',
        ['+ Save current stack']       = '+ 現在のスタックを保存',
        ['Choose a preset']            = 'プリセットを選択',
        ['Pick one on the left to see what it stacks, then load it.'] = '左から選ぶと中身が見られます。そのまま読み込めます。',
        ['Save your own with "+ Save current stack".'] = '「+ 現在のスタックを保存」で自分用を保存できます。',
        ['Installed build']            = '導入時の構成',
        ['Your loadout']               = 'あなたのロードアウト',
        ['Load this preset']           = 'このプリセットを読み込む',
        ['Click again']                = 'もう一度クリック',
        ['Save current here']          = '現在の構成をここに保存',
        ['Rename']                     = '名前を変更',
        ['Delete']                     = '削除',
        ['Type a name, Enter to keep it, Esc to cancel.'] = '名前を入力し、Enterで確定、Escでキャンセル。',
        ['Loading replaces your current stacks (Undo brings them back).'] = '読み込むと現在のスタックが置き換わります（元に戻すで復元）。',
        -- アーマー追加画面
        ['New stack']                  = '新しいスタック',
        ['Choose armor passive']       = 'アーマーのパッシブを選択',
        ['Cancel']                     = 'キャンセル',
        ['A second stack']             = '別のスタック',
        ['Each armor passive can carry its own stack. Pick one on the left,'] = 'アーマーのパッシブごとに別のスタックを持てます。左から選び、',
        ['then wear any armor that has that passive to get the stack.'] = 'そのパッシブを持つアーマーを着るとスタックが付きます。',
        ['Example: Med-Kit armor for a tank build, Siege-Ready armor for a gunner build.'] = '例：タンク構成には医療キット、ガンナー構成には包囲準備完了のアーマー。',
        -- 空の状態
        ['No armor forged yet']        = 'まだ鍛造していません',
        ['Empty']                      = '空',
        ['Nothing is stacked.']        = '何も重ねられていません。',
        ['How it works']               = '使い方',
        ['Forge your armor']           = 'アーマーを鍛造',
        ['Pick the armor passive you wear (for example Med-Kit),'] = '着ているアーマーのパッシブ（例：医療キット）を選び、',
        ['then tick any of the 31 passives to stack onto it and'] = '31種類のパッシブから好きなものを選んで重ね、',
        ['change their values. Everything applies at once.'] = '数値を変えましょう。すべてすぐに反映されます。',
        -- スタック画面
        ['Choose passives']            = 'パッシブを選択',
        ['BASE']                       = '基本',
        ['Specifications']             = '仕様',
        ['Remove from stack']          = 'スタックから外す',
        ['Add to stack']               = 'スタックに追加',
        ['BASE PERK']                  = '基本パッシブ',
        ['STACKED']                    = '適用中',
        ['NOT STACKED']                = '未適用',
        ["Your armor's own passive. Values here replace its own."] = 'アーマー本来のパッシブです。ここでの数値が元の数値に置き換わります。',
        ['Values you set are kept for when you add it.'] = '設定した数値は、追加したときのために保持されます。',
        ['When two passives change the same thing'] = '2つのパッシブが同じ項目を変えるとき',
        ['Stack all']                  = 'すべて重ねる',
        ['Strongest only']             = '最大のみ',
        ["This armor passive was not found in the game's data yet."] = 'このアーマーのパッシブはまだゲームデータに見つかっていません。',
        ["Another mod already changed this passive's data; Armory Forge leaves it alone."] = '別のModがこのパッシブのデータを変更済みです。Armory Forgeは触れません。',
        ['Copy code']                  = 'コードをコピー',
        ['Paste code']                 = 'コードを貼り付け',
        ['Turn all off']               = 'すべてオフ',
        -- メッセージ
        ['Nothing to undo']            = '元に戻せる操作がありません',
        ['Could not undo']             = '元に戻せませんでした',
        ['Turned everything off on this armor'] = 'このアーマーのパッシブをすべてオフにしました',
        ['Share code copied: paste it in the web builder, or a friend\'s panel'] = '共有コードをコピーしました。Web版や友達のパネルに貼り付けられます',
        ['Could not use the clipboard'] = 'クリップボードを使えません',
        ['The clipboard is empty']     = 'クリップボードが空です',
        ['No Armory Forge code on the clipboard'] = 'クリップボードにArmory Forgeのコードがありません',
        ['That preset could not be read'] = 'そのプリセットを読み込めませんでした',
        ['Panel back in place']        = 'パネルを元の位置に戻しました',
        ['ready']                      = '準備完了',

        -- ---- キー画面など
        ['Keys']                       = 'キー',
        ['Settings']                   = '設定',
        ['Panel']                      = 'パネル',
        ['Remove armor']               = 'アーマーを削除',
        ['Click again to remove']      = 'もう一度クリックで削除',
        ['Open / close this panel']    = 'このパネルを開く / 閉じる',
        ['Quick-swap loadouts']        = 'ロードアウトのクイック切替',
        ['OFF']                        = 'オフ',
        ['Picking the quick-swap key as the panel key turns quick-swap off.'] = 'クイック切替キーをパネルキーにすると、クイック切替はオフになります。',
        ['Quick-swap key turned off']  = 'クイック切替キーをオフにしました',
        ['- Smaller']                  = '- 小さく',
        ['+ Bigger']                   = '+ 大きく',
        ['Reset size and position']    = 'サイズと位置をリセット',
        ['Move the panel: drag its top strip.'] = 'パネルの移動：上部のバーをドラッグ。',
        ['Taller than the screen: turn the wheel outside a list to scroll it.'] = '画面より高い場合：リストの外でホイールを回すとスクロールします。',
        ['Fixed keys']                 = '固定キー',
        ['Search passives']            = 'パッシブを検索',
        ['Panel size']                 = 'パネルサイズ',
        ['Scroll a long list']         = '長いリストのスクロール',
        ['SHODAN Stat Editor uses F8 by default: pick another key here if you run both.'] = 'SHODAN Stat Editorは既定でF8を使います。両方使う場合は、ここで別のキーを選んでください。',
        ["Keys are saved with your loadout (hotkey / swap_hotkey in loadout.ini)."] = 'キーはロードアウトと一緒に保存されます（loadout.iniのhotkey / swap_hotkey）。',
        -- 検索 (Ctrl+F)
        ['SEARCH PASSIVES OR EFFECTS  (CTRL+F)'] = 'パッシブや効果を検索  (CTRL+F)',
        ['CLEAR']                      = 'クリア',
        -- コントローラー
        ['Select']                     = '選択',
        ['Back']                       = '戻る',
        ['Tabs']                       = 'タブ切替',
        ['Tick']                       = 'チェック',
        -- パッシブの説明と動作確認マーク
        ['Armors with this passive']   = 'このパッシブを持つアーマー',
        ['Point at a passive to see what it does and which armors have it.'] = 'パッシブにカーソルを合わせると、効果と対応アーマーが見られます。',
        ['Picked the wrong one? Open its tab and press REMOVE ARMOR.'] = '間違えましたか？ そのタブを開いて「アーマーを削除」を押してください。',
        ['CONFIRMED IN GAME']          = 'ゲーム内で確認済み',
        ['WORKS, NAME UNSURE']         = '動作する・名称は未確定',
        ['NO EFFECT SEEN']             = '効果を確認できず',
        ['UNTESTED']                   = '未検証',
        ['Stack summary']              = 'スタックの概要',
        ['STACK SUMMARY']              = 'スタックの概要',
        ['SUM']                        = '合計',
        ['WGT']                        = '重量',
        -- 6.2.1: 全アーマー
        ['OWN']                        = '本来',
        ['Any armor you wear']         = '着ているすべてのアーマー',
        ["The armor's own passive"]    = 'アーマー本来のパッシブ',
        ['Keep it']                    = '残す',
        ['Turn it off']                = 'オフにする',
        ['On every armor.']            = 'すべてのアーマーに適用。',
        ['Off: only the passives you tick count, whatever armor you wear.'] = 'オフ：どのアーマーを着ていても、選んだパッシブだけが有効です。',
        ['Kept: each armor keeps its own passive, and your stack goes on top.'] = '残す：各アーマーは本来のパッシブを保ち、その上にスタックが加わります。',
        ["Tick passives on the left; a passive's own tab (e.g. Med-Kit) still wins for its armors."] = '左でパッシブを選びます。そのパッシブ専用のタブ（例：医療キット）がある場合は、そちらが優先されます。',
        ['No armor records found yet. Load into your ship or a mission.'] = 'アーマーの記録がまだ見つかりません。艦かミッションに入ってください。',
        ['Added an Every armor stack: it stays whatever armor you wear'] = '全アーマーのスタックを追加しました。どのアーマーでも維持されます',
        ["The armors' own passives are off: only your picks count"] = 'アーマー本来のパッシブはオフです。選んだものだけが有効です',
        ['The armors keep their own passives'] = 'アーマーは本来のパッシブを保ちます',
        ['One stack for every armor you wear: pick passives and a weight once, then change armor as often as you like and the stack stays.'] = '着るすべてのアーマーに1つのスタック。パッシブと重量を一度選べば、アーマーを何度替えても維持されます。',
        ["It goes on every armor whose passive has no tab of its own. You can also turn the armors' own passives off, so only your picks count."] = '専用タブのないパッシブのアーマーすべてに付きます。アーマー本来のパッシブをオフにして、選んだものだけを有効にもできます。',
        ['Nothing stacked yet: tick passives on the left.'] = 'まだ何も重ねていません。左でパッシブを選んでください。',
        -- パッシブ入れ替え版 (Nexus)
        ["Passive Swap: give any armor another passive, at the game's values."] = 'パッシブ入れ替え：好きなアーマーに別のパッシブを、ゲーム本来の数値で付けられます。',
        ['Tick passives to stack them. Click a name to edit its values.'] = 'パッシブを選んで重ねます。名前をクリックすると数値を編集できます。',
        ['New swap']                   = '新しい入れ替え',
        ['Swap passive']               = 'パッシブを入れ替え',
        ['Swapped in']                 = '入れ替え後',
        ['its own passive']            = '本来のパッシブ',
        ['Original passive']           = '元のパッシブ',
        ['This armor keeps its own passive. Pick another on the left to swap it.'] = 'このアーマーは本来のパッシブのままです。左で別のものを選ぶと入れ替わります。',
        ['Game values']                = 'ゲームの数値',
        ["The passive is copied from the game's own data. One passive per armor, no stacking."] = 'パッシブはゲーム自身のデータからコピーされます。アーマー1つにつき1パッシブで、重ねられません。',
        ["Active: the game's own passive"] = '有効：ゲーム本来のパッシブ',
        ['Back to original']           = '元に戻す',
        ['Pick your armor']            = 'アーマーを選択',
        ['Pick the passive of the armor you wear on the left,'] = '左で、着ているアーマーのパッシブを選び、',
        ['then choose which passive it should have instead.'] = '代わりに付けたいパッシブを選びます。',
        ['Example: Med-Kit armor with Siege-Ready.'] = '例：医療キットのアーマーに包囲準備完了を付ける。',
        ["then choose which of the game's passives it should"] = '次に、ゲームのパッシブの中から',
        ["have instead. The values are the game's own."] = '代わりに付けるものを選びます。数値はゲーム本来のものです。',
        ['Nothing is swapped.']        = '入れ替えているパッシブはありません。',
        ['None yet. Save your current swaps.'] = 'まだありません。現在の入れ替えを保存しましょう。',
        ['+ Save current swaps']       = '+ 現在の入れ替えを保存',
        ['Save your own with "+ Save current swaps".'] = '「+ 現在の入れ替えを保存」で自分用を保存できます。',
        ['Loading replaces your current swaps (Undo brings them back).'] = '読み込むと現在の入れ替えが置き換わります（元に戻すで復元）。',
        ['Pick it, then choose the passive these armors should have.'] = 'これを選び、これらのアーマーに付けるパッシブを選びます。',
        ['Pick it, then wear any of these armors to get the stack.'] = 'これを選び、いずれかのアーマーを着るとスタックが付きます。',
        -- ---- ガイド / 重量 / レポート / 着用中の枠
        ['Guide']                      = 'ガイド',
        ['How to use it']              = '使い方',
        ['Controls']                   = '操作',
        ['Keyboard']                   = 'キーボード',
        ['Mouse']                      = 'マウス',
        ['Controller']                 = 'コントローラー',
        ['Wearing']                    = '着用中',
        ['Looking for your armor...']  = 'アーマーを探しています...',
        ['Shows a few seconds after loading in.'] = '読み込みの数秒後に表示されます。',
        ['Passive not known to the mod'] = 'このModが知らないパッシブ',
        ['Recipes']                    = 'レシピ',
        ['RCP']                        = 'レシピ',
        ['Armor passive combos']       = 'アーマーパッシブの組み合わせ',
        ['Pick a recipe to tick all its passives at once. Save your own from what is ticked now.'] = 'レシピを選ぶと、そのパッシブをまとめてチェックします。今チェックしているものを自分のレシピとして保存もできます。',
        ['Only this']                  = 'これだけ',
        ['+ Save ticked passives as recipe'] = '+ チェック中のパッシブをレシピとして保存',
        ['None of these passives are in this game build.'] = 'このゲームのバージョンにはこれらのパッシブがありません。',
        ['Armor weight']               = 'アーマーの重量',
        ["An armor's weight class sets its speed, stamina regen and base armor rating. Pick one and the armor keeps its look."]
                                       = 'アーマーの重量区分で、移動速度、スタミナ回復、基本のアーマー評価が決まります。選んでも見た目は変わりません。',
        ['Game']                       = 'ゲーム値',
        ['Light']                      = '軽量',
        ['Medium']                     = '中量',
        ['Heavy']                      = '重量',
        ['As above']                   = '上に同じ',
        ['What each weight gives (game values)'] = '各重量区分の効果（ゲームの数値）',
        ['Game keyboard and mouse while open'] = '開いている間のゲームのキー・マウス入力',
        ['The game gets no keyboard or mouse while the panel is open'] = 'パネルを開いている間、ゲームにキーボードとマウスは届きません',
        ['The game gets your keyboard and mouse while the panel is open'] = 'パネルを開いている間も、ゲームにキーボードとマウスが届きます',
        ['Blocked']                    = '遮断',
        ['Let through']                = '通す',
        ['Mascot']                     = 'マスコット',
        ['On']                         = 'オン',
        ['Off']                        = 'オフ',
        ['Panel size (CTRL 0 resets size and position)'] = 'パネルサイズ（CTRL 0でサイズと位置をリセット）',
        ['Search passives and effects'] = 'パッシブと効果を検索',
        ['Open / close the panel']     = 'パネルを開く / 閉じる',
        ['Swap to the next preset (panel closed)'] = '次のプリセットに切替（パネルを閉じた状態で）',
        ['Quick-swap key: off']        = 'クイック切替キー：オフ',
        ['Set / cancel a typed value'] = '入力した数値を確定 / 取り消し',
        ['Tabs, names, ticks and buttons'] = 'タブ、名前、チェック、ボタン',
        ['Scroll the list under the cursor'] = 'カーソル下のリストをスクロール',
        ['The top strip moves the panel'] = '上部のバーでパネルを移動',
        ['Move between controls']      = '項目間の移動',
        ['Back / close']               = '戻る / 閉じる',
        ['Tick the chosen passive']    = '選んだパッシブをチェック',
        ['Scroll']                     = 'スクロール',
        ['Something wrong?']           = '問題がありますか？',
        ['Copy a report and paste it in your bug report on the mod page.'] = 'レポートをコピーして、Modページの不具合報告に貼り付けてください。',
        ['Copy problem report']        = '問題レポートをコピー',
        ['Problem report copied: paste it in your bug report'] = '問題レポートをコピーしました。不具合報告に貼り付けてください',
        ['While the panel is open the game ignores your keyboard and mouse (Keys tab: Blocked / Let through). Something wrong? Keys tab, Copy problem report.']
                                       = 'パネルを開いている間、ゲームはキーボードとマウスを無視します（キー画面：遮断 / 通す）。問題がある場合は、キー画面の「問題レポートをコピー」を使ってください。',
        ['Wear the armor you want to boost. The panel opens on its passive\'s tab, and the box at the top shows what you\'re wearing.']
                                       = '強化したいアーマーを着ます。パネルはそのパッシブのタブで開き、上の枠に着ているアーマーが表示されます。',
        ['Wear the armor you want to change. The panel opens on its passive\'s tab, and the box at the top shows what you\'re wearing.']
                                       = '変更したいアーマーを着ます。パネルはそのパッシブのタブで開き、上の枠に着ているアーマーが表示されます。',
        ['No tab for it yet? Click that box, or + Armor and pick the passive of the armor you wear.']
                                       = 'タブがまだない場合は、その枠をクリックするか、「+ アーマー」で着ているアーマーのパッシブを選びます。',
        ['On its tab, choose the passive it should have instead. Original puts the game\'s own back.']
                                       = 'そのタブで、代わりに付けたいパッシブを選びます。「元のパッシブ」でゲーム本来のものに戻せます。',
        ['It applies at once. Re-select the armor in the armory if the card still shows the old passive.']
                                       = 'すぐに反映されます。カードに古いパッシブが表示されたままなら、兵器庫でアーマーを選び直してください。',
        ['Tick passives on the left: they stack onto every armor with that tab\'s passive.']
                                       = '左でパッシブを選ぶと、そのタブのパッシブを持つすべてのアーマーに重なります。',
        ['Click a passive\'s name to see its values on the right; -- - + ++ change them, or click a value and type one.']
                                       = 'パッシブの名前をクリックすると右に数値が出ます。-- - + ++ で変更するか、数値をクリックして直接入力します。',
        ['Armor weight: make that passive\'s armors light, medium or heavy, or only the armor you\'re wearing.']
                                       = 'アーマーの重量：そのパッシブのアーマーを軽量・中量・重量にします。着ているアーマーだけにもできます。',
        ['Copy code / Paste code share a loadout with a friend.'] = 'コードをコピー / 貼り付けで、ロードアウトを友達と共有できます。',
        ['Copy code / Paste code share a loadout (the web builder reads them too).'] = 'コードをコピー / 貼り付けでロードアウトを共有できます（Web版ビルダーでも読めます）。',
        ['Presets: save loadouts, then the quick-swap key swaps between them without opening the panel.']
                                       = 'プリセット：ロードアウトを保存すると、パネルを開かずにクイック切替キーで切り替えられます。',
        ['Changes apply at once and are saved when you close the panel. Solo and private lobbies only.']
                                       = '変更はすぐに反映され、パネルを閉じると保存されます。ソロとプライベートロビー専用です。',
    },

    -- ---------------------------------------------------------------- 2. 数字や名前を含む文
    -- { Luaパターン, 置換 }。^...$ で文全体に一致させます。パネルはラベルを大文字にするので、
    -- 同じ文が原文と全大文字の両方に登録されます。
    pat = {
        -- 6.2.1: 全アーマー
        { '^(.+)  %-  ANY ARMOR YOU WEAR$',                  '%1  -  着ているすべてのアーマー' },
        { '^(.+)  %-  YOUR ARMOR$',                          '%1  -  あなたのアーマー' },
        { "^ARMOR'S OWN PASSIVE: KEEP$",                     'アーマー本来のパッシブ：残す' },
        { "^ARMOR'S OWN PASSIVE: OFF$",                      'アーマー本来のパッシブ：オフ' },
        { '^This stack goes on every armor whose passive has no tab of its own %((%d+) passive%(s%) now%)%. Change armor as often as you like: the stack and its weight stay%.$',
          'このスタックは、専用タブのないパッシブのアーマーすべてに付きます（現在 %1 パッシブ）。アーマーを何度替えても、スタックと重量は維持されます。' },
        { '^Applies to all (%d+) armor%(s%) with no tab of their own%. Passives on the armor add to it %(e%.g%. Extra Padding %+50 armor%)%.$',
          '専用タブのない %1 個のアーマーすべてに適用されます。アーマー側のパッシブは上乗せされます（例：追加パッド +50 アーマー評価）。' },
        { '^(%d+) passive%(s%) stacked on (%d+) armor passive%(s%) without their own tab, own passives off$',
          '%1 個のパッシブを、専用タブのない %2 個のアーマーパッシブに適用中（本来のパッシブはオフ）' },
        { '^(%d+) passive%(s%) stacked on (%d+) armor passive%(s%) without their own tab$',
          '%1 個のパッシブを、専用タブのない %2 個のアーマーパッシブに適用中' },
        { '^(.+): Every armor stack, (%d+) passive%(s%), own passive off %(tab (%d+)%)$', '%1：全アーマーのスタック、%2 パッシブ、本来のパッシブはオフ（タブ %3）' },
        { '^(.+): Every armor stack, (%d+) passive%(s%), own passive off$', '%1：全アーマーのスタック、%2 パッシブ、本来のパッシブはオフ' },
        { '^(.+): Every armor stack, (%d+) passive%(s%) %(tab (%d+)%)$', '%1：全アーマーのスタック、%2 パッシブ（タブ %3）' },
        { '^(.+): Every armor stack, (%d+) passive%(s%)$',   '%1：全アーマーのスタック、%2 パッシブ' },
        { '^(.+): (%d+) passive%(s%) stacked %(tab (%d+)%)$', '%1：%2 パッシブを適用中（タブ %3）' },
        { '^(.+): tab (%d+), nothing ticked yet %(tab (%d+)%)$', '%1：タブ %2、まだ何も選択されていません' },
        { '^GAME VALUE (.+)$',                               'ゲーム値 %1' },
        { '^Armor (0x%x+)$',                                 'アーマー %1' },
        { '^Applies to: (.+)$',                              '対象：%1' },
        { '^(.+) in game cycles your loadouts %(or the standard ones%)%.$',
          'ゲーム中に %1 でロードアウトを順に切り替えます（なければ標準のもの）。' },
        { "^(%d+) ON$",                                  '%1 件オン' },
        { "^(%d+) PASSIVES$",                           'パッシブ %1 個' },
        { "^(%d+) PASSIVES  YOURS$",                    'パッシブ %1 個  自分用' },
        { "^(%d+) SAVED$",                               '%1 件保存済み' },
        { "^Armor stack (%d+) / (%d+)$",                 'アーマースタック %1 / %2' },
        { "^Undo %((%d+)%)$",                            '元に戻す（%1）' },
        { "^Reset (.+)$",                                '%1 をリセット' },
        { "^On (.+) armor%.$",                           '%1 のアーマーに適用。' },
        { "^(.+) armor$",                                '%1 のアーマー' },
        { "^Panel size (%d+)%%$",                        'パネルサイズ %1%%' },
        { "^Press (.+) to forge your armor$",            '%1 を押してアーマーを鍛造' },
        { "^your preset (%d+) of (%d+)$",                'あなたのプリセット %1 / %2' },
        { "^preset (%d+) of (%d+)$",                     'プリセット %1 / %2' },
        { "^ARMORY FORGE  %-  (.+)$",                    '兵器工廠 - %1' },
        { "^Added a stack for (.+) armor$",              '%1 のアーマーにスタックを追加しました' },
        { "^Removed the (.+) stack %(the game's own values are back%)$",
          '%1 のスタックを削除しました（ゲーム本来の数値に戻りました）' },
        { "^Loaded the pasted code: (.+)$",              '貼り付けたコードを読み込みました：%1' },
        { '^Saved as "(.+)"$',                           '「%1」として保存しました' },
        { "^Undone %((%d+) more%)$",                     '元に戻しました（あと %1 回戻せます）' },
        { "^Not a number: (.+)$",                        '数値ではありません：%1' },
        { '^Deleted "(.+)"$',                            '「%1」を削除しました' },
        { '^Saved your current stacks into "(.+)"$',     '現在のスタックを「%1」に保存しました' },
        { '^Saved%. Type a name for it, or press Enter to keep "(.+)"%.$',
          '保存しました。名前を入力するか、Enterで「%1」のままにします。' },
        { "^GAME VALUE (%S+)%s+WAS (%S+)$",              'ゲーム値 %1（元は %2）' },
        { "^Reading the game's armor passives%.%.%. %((%d+) of (%d+) found%)$",
          'ゲームのアーマーパッシブを読み込み中...（%2 件中 %1 件見つかりました）' },
        { "^(%d+) passive%(s%) stacked, %+(%d+) row%(s%) in the game's data %- (%d+) overlap%(s%)$",
          '%1 個のパッシブを適用中。ゲームデータに %2 行追加 - 重複 %3 件' },
        { "^(%d+) passive%(s%) stacked, %+(%d+) row%(s%) in the game's data$",
          '%1 個のパッシブを適用中。ゲームデータに %2 行追加' },
        { "^(%d+) passive%(s%), (%d+) value%(s%) changed, (.+)$",
          '%1 個のパッシブ、%2 項目の数値を変更、%3' },
        { "^(.+) in game cycles your loadouts %(or the standard ones%)$",
          'ゲーム中に %1 でロードアウトを順に切り替えます（なければ標準のもの）' },
        -- ---- キー画面などの文
        { "^The panel now opens with (.+)$",             'パネルは %1 で開くようになりました' },
        { "^Quick%-swap is now (.+)$",                   'クイック切替キーを %1 にしました' },
        { '^Size: (%d+)%%  %(Ctrl %+ / Ctrl %-, or %[%-] %[%+%] at the top%)$',
          'サイズ：%1%%（Ctrl + / Ctrl - 、または上部の [-] [+]）' },
        { '^Nothing matches "(.+)"%.$',                  '「%1」に一致するものはありません' },
        { '^%+(%d+) more$',                              'ほか %1 件' },
        { '^Everything on this armor together: its own passive plus (%d+) stacked%. An estimate: how the game combines stacked values is not confirmed yet%.$',
          'このアーマーの効果の合計：本来のパッシブと、重ねた %1 個のパッシブ。推定値です。重ねた数値をゲームがどう合算するかは未確認です。' },
        { '^Added (.+) armor$',                          '%1 のアーマーを追加しました' },
        { '^Armor (%d+) / (%d+)$',                       'アーマー %1 / %2' },
        { '^Every (.+) armor has (.+) instead of its own passive%.$',
          '%1 のアーマーは、本来のパッシブの代わりに %2 を持ちます。' },
        { "^Waiting for (.+) in the game's data%.%.%.$", 'ゲームデータの %1 を待っています...' },
        { '^Active: (.+) armor has (.+)$',               '有効：%1 のアーマーは %2 を持っています' },
        { '^(.+) armor now has (.+)$',                   '%1 のアーマーは %2 になりました' },
        { "^(.+) armor has its own passive again$",      '%1 のアーマーは本来のパッシブに戻りました' },
        { '^Original: (.+)$',                            '元：%1' },
        { '^has (.+)$',                                  '%1 を持つ' },
        -- ---- 重量・入れ替えなどの文
        { "^Presets: save loadouts, then (.+) swaps between them without opening the panel%.$",
          'プリセット：ロードアウトを保存すると、パネルを開かずに %1 で切り替えられます。' },
        { '^(.+): no swap yet%. Click to add its tab$',      '%1：まだ入れ替えなし。クリックでタブを追加' },
        { '^(.+): nothing stacked%. Click to add its tab$',  '%1：まだ何も重ねていません。クリックでタブを追加' },
        { '^(.+): keeps its own passive$',                   '%1：本来のパッシブのまま' },
        { '^(.+): keeps its own passive %(tab (%d+)%)$',     '%1：本来のパッシブのまま（タブ %2）' },
        { '^(.+) %-> (.+) %(tab (%d+)%)$',                   '%1 → %2（タブ %3）' },
        { '^(.+) %-> (.+)$',                                 '%1 → %2' },
        { '^(.+): (%d+) passive%(s%) stacked$',              '%1：%2 パッシブを適用中' },
        { '^(.+): tab (%d+), nothing ticked yet$',           '%1：タブ %2、まだ何も選択されていません' },
        { '^ARMOR WEIGHT: GAME$',                            'アーマーの重量：ゲーム値' },
        { '^ARMOR WEIGHT: LIGHT$',                           'アーマーの重量：軽量' },
        { '^ARMOR WEIGHT: MEDIUM$',                          'アーマーの重量：中量' },
        { '^ARMOR WEIGHT: HEAVY$',                           'アーマーの重量：重量' },
        { '^ARMOR (.+)    SPEED (.+)    STAMINA REGEN (.+)$', 'アーマー評価 %1    速度 %2    スタミナ回復 %3' },
        { '^Applies to all (%d+) armor%(s%) with (.+)%. Passives on the armor add to it %(e%.g%. Extra Padding %+50 armor%)%.$',
          '%2 を持つ %1 個のアーマーすべてに適用されます。アーマー側のパッシブは上乗せされます（例：追加パッド +50 アーマー評価）。' },
        { "^The armor records for (.+) were not found yet, so the weight can't apply%. Load into your ship or a mission%.$",
          '%1 のアーマー記録がまだ見つからないため、重量を適用できません。艦かミッションに入ってください。' },
        { '^WEAR ANY OF: (.+)$',                             '次のいずれかを着用：%1' },
        { "^Only the armor you're wearing: (.+)$",           '着ているアーマーのみ：%1' },
        { '^(.+): light weight$',                            '%1：軽量' },
        { '^(.+): medium weight$',                           '%1：中量' },
        { '^(.+): heavy weight$',                            '%1：重量' },
        { '^(.+): same as its passive$',                     '%1：パッシブと同じ' },
        { '^(.+) armors: light weight$',                     '%1 のアーマー：軽量' },
        { '^(.+) armors: medium weight$',                    '%1 のアーマー：中量' },
        { '^(.+) armors: heavy weight$',                     '%1 のアーマー：重量' },
        { '^(.+) armors: their own weight$',                 '%1 のアーマー：本来の重量' },
        { '^Added (.+) %(your armor%)$',                     '%1 を追加しました（あなたのアーマー）' },
    },

    -- ---------------------------------------------------------------- 3. 句の中で置き換えない語
    -- 短い一般語は、文の内部では置き換えません（Scout、Tankなど）。
    no_frag = { scout = true, tank = true, stealth = true, gunner = true, survivor = true },
    -- the end of a string translated on its own, the rest looked up again
    suffix = {
        { ' (name is a guess)', '（名称は推測）' },
    },
    frag = {
        { ', stack all',        '、すべて重ねる', 'ui' },
        { ', strongest only',   '、最大のみ',     'ui' },
        { ',stack all',         '、すべて重ねる', 'ui' },
        { '，stack all',        '、すべて重ねる', 'ui' },
        { '，strongest only',   '、最大のみ',     'ui' },
        { ' armor',             ' のアーマー',    'ui' },
        { ' (name is a guess)', '（名称は推測）', 'ui' },
        { '(weapon stat)',      '（武器ステータス）', 'effect' },
    },

    -- ---------------------------------------------------------------- 5. アーマーのパッシブ名
    -- ゲーム公式の日本語テキスト（passive-text.json から生成）
    perk = {
        ['Extra Padding'] = '追加パッド',
        ['Scout'] = '偵察',
        ['Fortified'] = '装甲強化',
        ['Electrical Conduit'] = '導電管',
        ['Engineering Kit'] = '工作キット',
        ['Med-Kit'] = '医療キット',
        ['Servo-Assisted'] = 'サーボアシスト付',
        ['Democracy Protects'] = '民主主義の加護',
        ['Reinforced Epaulettes'] = '強化肩章',
        ['Inflammable'] = '耐熱性',
        ['Peak Physique'] = 'ピークフィジーク',
        ['Advanced Filtration'] = '高機能ろ過',
        ['Unflinching'] = '不動',
        ['Acclimated'] = '順応',
        ['Siege-Ready'] = '包囲準備完了',
        ['Integrated Explosives'] = '内蔵式爆薬',
        ['Gunslinger'] = 'ガンスリンガー',
        ['Adreno-Defibrillator'] = 'アドレナリン除細動器',
        ['Ballistic Padding'] = 'バリスティックパッド',
        ['Desert Stormer'] = 'デザートストーマー',
        ['Feet First'] = 'フィートファースト',
        ['Reduced Signature'] = '探知抑制',
        ['Rock-Solid'] = '頑丈',
        ['Supplemental Adrenaline'] = 'アドレナリンサプリメント',
        ['Concussive Padding, Reinforced'] = '耐衝撃パッド（強化）',
        ['Concussive Padding, Grenadier'] = '耐衝撃パッド（グレネード）',
        ['Concussive Padding, Hazmat'] = '耐衝撃パッド（有害物質）',
        ['Oxygenator'] = '酸素供給器',
        ['Kinetic Displacement Mitigation'] = '移動によるズレ軽減',
        ['Blunt-Force Mitigation'] = '鈍的ダメージ緩和',
        ['True Grit'] = '真の根性',
        ['Standard Issue'] = '標準装備',
        ['Every armor'] = 'すべてのアーマー',
    },

    -- ---------------------------------------------------------------- 6. 効果名
    -- パネルに出るのは label_of(e) の結果（keyの下線を空白にして先頭を大文字にしたもの）。
    -- 武器ステータス系は末尾に "(weapon stat)" が付くので、表示どおりの文字列で登録します。
    effect = {
        ['Armor rating']               = 'アーマー評価',
        ['Radar ping']                 = 'レーダースキャン間隔',
        ['Detection radius']           = '敵の検知範囲',
        ['Crouch prone recoil']        = 'しゃがみ・うつ伏せ時の反動',
        ['Explosive damage taken']     = '爆発ダメージ耐性',
        ['Arc damage taken']           = '放電ダメージ耐性',
        ['Arc secondary']              = '放電の連鎖［不明］',
        ['Throwables']                 = 'グレネードの追加数',
        ['Stims']                      = '回復薬の追加数',
        ['Stim duration']              = '回復薬の効果時間',
        ['Throw range']                = '投擲距離',
        ['Limb health']                = '四肢の体力',
        ['Death save']                 = '致命傷を耐える確率',
        ['Chest bleed']                = '胸部出血時に受ける出血ダメージ',
        ['Primary reload speed']       = 'メインウェポンのリロード速度',
        ['Limb injury avoid']          = '四肢の重傷回避',
        ['Melee damage']               = '近接攻撃ダメージ',
        ['Fire damage taken']          = '炎ダメージ耐性',
        ['Ergonomics']                 = 'エルゴノミクス',
        ['Melee flag']                 = '近接フラグ［効果不明］',
        ['Gas damage taken']           = 'ガスダメージ耐性',
        ['Flinch']                     = 'ひるみ',
        ['Elemental damage taken']     = '炎・ガス・酸・電気ダメージ耐性',
        ['Ammo capacity']              = '弾薬容量',
        ['Death explosion delay']      = '死亡後の爆発までの時間',
        ['Sidearm reload speed']       = 'ハンドガンのリロード速度',
        ['Sidearm draw speed']         = 'ハンドガンの切り替え速度',
        ['Sidearm recoil']             = 'ハンドガンの反動',
        ['Revive marker']              = '短時間の復活',
        ['Chest damage taken']         = '胸部ダメージ耐性',
        ['Movement noise']             = '移動音',
        ['Poi range']                  = '地点識別範囲',
        ['Leg injury immunity']        = '脚部負傷の耐性',
        ['Stagger']                    = 'よろめき',
        ['Stamina on damage']          = '被ダメージ時のスタミナ回復',
        ['Impact damage taken']        = '衝撃ダメージ耐性',
        ['Move speed a']               = '移動速度 A',
        ['Move speed b']               = '移動速度 B',
        ['Slide flag']                 = 'スライディングフラグ［不明］',
        ['Support reload speed']       = '支援武器のリロード速度',
        -- 武器ステータス（stat）系：stat_ を外し、下線を空白にし、先頭を大文字にして
        -- " (weapon stat)" を付けた最終的な文字列で登録します。
        ['Flinch (weapon stat)']          = 'ひるみ（武器ステータス）',
        ['Ammo capacity (weapon stat)']   = '弾薬容量（武器ステータス）',
        ['Primary reload (weapon stat)']  = 'メインウェポンのリロード（武器ステータス）',
        ['Support reload (weapon stat)']  = '支援武器のリロード（武器ステータス）',
        ['Sidearm reload (weapon stat)']  = 'ハンドガンのリロード（武器ステータス）',
        ['Sidearm draw (weapon stat)']    = 'ハンドガンの切り替え（武器ステータス）',
        ['Sidearm recoil (weapon stat)']  = 'ハンドガンの反動（武器ステータス）',
    },

    -- ---------------------------------------------------------------- 7. 数値の単位の説明
    unit = {
        ['damage resist (100% = none taken)'] = 'ダメージ耐性（100% = 受けない）',
        ['change from normal']                = '通常からの増減',
        ['armor rating']                      = 'アーマー評価',
        ['extra']                             = '追加数',
        ['seconds']                           = '秒',
        ['value (flag)']                      = '値（フラグ）',
    },

    -- ---------------------------------------------------------------- 8. 組み込みプリセット名
    preset = {
        ['Kitchen Sink']   = 'なんでも入り',
        ['Tank']           = 'タンク',
        ['Stealth']        = 'ステルス',
        ['Survivor']       = 'サバイバー',
        ['Demolitionist']  = '爆破担当',
        ['Gunner']         = 'ガンナー',
        ['My preset']      = 'マイプリセット',
    },

    -- ---------------------------------------------------------------- 9. パッシブの説明
    -- tools/passives.json から picker.py が作る PASSIVE_INFO の文。1行で描かれるので
    -- 文全体の完全一致で引きます。
    desc = {
        ['50% fire, gas, acid and arc resist.'] = '炎・ガス・酸・電気のダメージ耐性 50%。',
        ['One short revive after a death (body intact); stims last 2 s longer; 50% arc resist.'] = '死亡後に一度だけ短時間復活（遺体が無傷の場合）。回復薬の効果時間 +2秒。放電ダメージ耐性 50%。',
        ['80% gas resist.'] = 'ガスダメージ耐性 80%。',
        ['25% chest and 25% explosive resist; no chest bleeding.'] = '胸部ダメージ耐性 25%、爆発ダメージ耐性 25%。胸部出血なし。',
        ['Harder to knock down; 30% impact resist; higher armor rating.'] = '倒されにくい。衝撃ダメージ耐性 30%。アーマー評価が高い。',
        ['50% explosive resist; +2 grenades.'] = '爆発ダメージ耐性 50%。グレネード +2。',
        ['50% explosive resist; 25% gas resist; 30% less sidearm recoil.'] = '爆発ダメージ耐性 50%。ガスダメージ耐性 25%。ハンドガンの反動 -30%。',
        ['50% explosive resist; higher armor rating.'] = '爆発ダメージ耐性 50%。アーマー評価が高い。',
        ['50% chance to survive a lethal hit; no chest bleeding.'] = '致命傷を 50% の確率で耐える。胸部出血なし。',
        ['40% fire, gas, acid and arc resist; +20% throw range.'] = '炎・ガス・酸・電気のダメージ耐性 40%。投擲距離 +20%。',
        ['95% arc resist.'] = '放電ダメージ耐性 95%。',
        ['30% less recoil crouched or prone; +2 grenades.'] = 'しゃがみ・うつ伏せ時の反動 -30%。グレネード +2。',
        ['Higher armor rating.'] = 'アーマー評価が高い。',
        ['50% quieter movement; +30% point-of-interest range; no leg injuries.'] = '移動音 -50%。地点識別範囲 +30%。脚部を負傷しない。',
        ['30% less recoil crouched or prone; 50% explosive resist.'] = 'しゃがみ・うつ伏せ時の反動 -30%。爆発ダメージ耐性 50%。',
        ['Sidearms: +40% reload speed, +50% draw speed, 70% less recoil.'] = 'ハンドガン：リロード速度 +40%、切り替え速度 +50%、反動 -70%。',
        ['75% fire resist.'] = '炎ダメージ耐性 75%。',
        ['Armor explodes 1.5 s after you die; +2 grenades.'] = '死亡の 1.5秒後にアーマーが爆発。グレネード +2。',
        ['50% fire resist; 50% chance to avoid limb injury; 30% impact resist.'] = '炎ダメージ耐性 50%。四肢の重傷を 50% の確率で回避。衝撃ダメージ耐性 30%。',
        ['+2 stims; stims last 2 s longer.'] = '回復薬 +2。回復薬の効果時間 +2秒。',
        ['Faster walking and running; faster, longer slides.'] = '歩行・ダッシュが速くなる。スライディングが速く長くなる。',
        ['+40% melee damage; better weapon handling.'] = '近接攻撃ダメージ +40%。武器の取り回しが向上。',
        ['50% quieter movement; enemies spot you from 40% closer.'] = '移動音 -50%。敵に検知される範囲 -40%。',
        ['+30% primary reload; 50% chance to avoid limb injury; +20% melee damage.'] = 'メインウェポンのリロード +30%。四肢の重傷を 50% の確率で回避。近接攻撃ダメージ +20%。',
        ['+40% melee damage; harder to knock down.'] = '近接攻撃ダメージ +40%。倒されにくい。',
        ['Map markers scan for enemies every 2 s; enemies spot you from 30% closer.'] = 'マップのマーカーが 2秒ごとに敵をスキャン。敵に検知される範囲 -30%。',
        ['+30% throw range; +50% limb health.'] = '投擲距離 +30%。四肢の体力 +50%。',
        ['+30% primary reload; +20% ammo for all weapons (not backpacks).'] = 'メインウェポンのリロード +30%。全武器の弾薬 +20%（武器バックパックを除く）。',
        ['Taking damage restores stamina; higher armor rating.'] = 'ダメージを受けるとスタミナが回復。アーマー評価が高い。',
        ['+30% support weapon reload; better weapon handling.'] = '支援武器のリロード +30%。武器の取り回しが向上。',
        ['Less flinch when hit; higher armor rating; map markers scan every 2 s.'] = '被弾時のひるみが少ない。アーマー評価が高い。マップのマーカーが 2秒ごとにスキャン。',
    },

    -- ---------------------------------------------------------------- 10. アーマー名
    -- ゲーム公式の日本語名（armor-names.json の names.ja から生成。鎧・ヘルメット・
    -- ケープで同じ名前は1つにまとめています）
    armor = {
        ['A-35 Recon'] = 'A-35 リーコン',
        ['A-9 Helljumper'] = 'A-9 ヘルジャンパー',
        ['AC-1 Dutiful'] = 'AC-1 デューティフル',
        ['AC-2 Obedient'] = 'AC-2 オビディエント',
        ['AD-11 Livewire'] = 'AD-11 ライブワイヤー',
        ['AD-26 Bleeding Edge'] = 'AD-26 ブリーディング・エッジ',
        ['AD-49 Apollonian'] = 'AD-49 アポロニアン',
        ['AF-02 Haz-Master'] = 'AF-02 ハザードマスター',
        ['AF-50 Noxious Ranger'] = 'AF-50 毒使い',
        ['AF-52 Lockdown'] = 'AF-52 ロックダウン',
        ['AF-91 Field Chemist'] = 'AF-91 フィールドケミスト',
        ['Against the Tyrant Cloud'] = '暴君の雲に抗う者',
        ['Agent of Oblivion'] = '忘却の代行者',
        ['B-01 Tactical'] = 'B-01 タクティカル',
        ['B-02 Gloom Warden'] = 'B-02 グルーム・ウォーデン',
        ['B-08 Light Gunner'] = 'B-08 ライトガンナー',
        ['B-16 Battle-Scarred Veteran'] = 'B-16 歴戦の勇士',
        ['B-22 Model Citizen'] = 'B-22 模範市民',
        ['B-24 Enforcer'] = 'B-24 エンフォーサー',
        ['B-27 Fortified Commando'] = 'B-27 フォーティファイドコマンドー',
        ['BFM-16 Tanker'] = 'BFM-16 タンカー',
        ['BFM-220 Ironclad'] = 'BFM-220 アイアンクラッド',
        ['BFM-77 Reformer'] = 'BFM-77 リフォーマー',
        ['BP-20 Correct Officer'] = 'BP-20 正規将校章',
        ['BP-32 Jackboot'] = 'BP-32 ジャックブート',
        ['BP-77 Grand Juror'] = 'BP-77 大陪審員',
        ['Badge of Order'] = '秩序の記章',
        ['Bastion of Integrity'] = '誠実の砦',
        ['Beacon of Mercy'] = '慈悲の灯',
        ['Blazing Samaritan'] = '怒れる善人',
        ['Botslayer'] = 'ロボットスレイヤー',
        ['Bugslayer'] = 'バグスレイヤー',
        ['CE-07 Demolition Specialist'] = 'CE-07 デモリションスペシャリスト',
        ['CE-101 Guerilla Gorilla'] = 'CE-101 ゲリラゴリラ',
        ['CE-27 Ground Breaker'] = 'CE-27 グラウンドブレーカー',
        ['CE-35 Trench Engineer'] = 'CE-35 トレンチエンジニア',
        ['CE-64 Grenadier'] = 'CE-64 グレネディア',
        ['CE-67 Titan'] = 'CE-67 タイタン',
        ['CE-74 Breaker'] = 'CE-74 ブレイカー',
        ['CE-81 Juggernaut'] = 'CE-81 ジャガーノート',
        ['CM-09 Bonesnapper'] = 'CM-09 ボーンスナッパー',
        ['CM-10 Clinician'] = 'CM-10 クリニシャン',
        ['CM-14 Physician'] = 'CM-14 フィジシャン',
        ['CM-17 Butcher'] = 'CM-17 ブッチャー',
        ['CM-21 Trench Paramedic'] = 'CM-21 トレンチパラメディック',
        ['CPG-48 Sapper'] = 'CPG-48 サッパー',
        ['CPH-26 Commandant'] = 'CPH-26 コマンダント',
        ['CPR-80 Bulwark'] = 'CPR-80 ブルワーク',
        ['CW-22 Kodiak'] = 'CW-22 コディアック',
        ['CW-36 Winter Warrior'] = 'CW-36 ウィンターウォリアー',
        ['CW-4 Arctic Ranger'] = 'CW-4 極地レンジャー',
        ['CW-9 White Wolf'] = 'CW-9 白狼',
        ['Camo Cloak'] = 'カモフラージュマント',
        ['City Fighter\'s Resolve'] = '都市戦闘員の覚悟',
        ['Cloak of Posterity\'s Gratitude'] = '子孫からの感謝のマント',
        ['Conductor of Brilliance'] = '輝きの指揮者',
        ['Cover of Darkness'] = '闇からの庇護',
        ['Crest of the Unsullied'] = '無垢なる紋章',
        ['Cresting Honor'] = '至上の栄誉',
        ['DP-00 Tactical'] = 'DP-00 タクティカル',
        ['DP-11 Champion of the People'] = 'DP-11 人民の闘士',
        ['DP-40 Hero of the Federation'] = 'DP-40 連邦の英雄',
        ['DP-53 Savior of the Free'] = 'DP-53 自由の救済者',
        ['DP-8 Mountain-Scaled'] = 'DP-8 マウンテンスケール',
        ['DS-10 Big Game Hunter'] = 'DS-10 ビッグゲーム・ハンター',
        ['DS-191 Scorpion'] = 'DS-191 スコーピオン',
        ['DS-42 Federation\'s Blade'] = 'DS-42 連邦の刃',
        ['De-Forester\'s Sailcloth'] = '伐採者の帆布',
        ['Defender of Our Dream'] = '夢の守護者',
        ['Defender of the Wall'] = '壁の守護者',
        ['Diagram of the Noblest Payload'] = '高潔なる積載物の図',
        ['Dignity of Toil'] = '労働の尊厳',
        ['Dissident\'s Nightmare'] = '反逆者の悪夢',
        ['Drape of Glory'] = '栄光のマント',
        ['EX-00 Prototype X'] = 'EX-00 プロトタイプx',
        ['EX-03 Prototype 3'] = 'EX-03 プロトタイプ3',
        ['EX-16 Prototype 16'] = 'EX-16 プロトタイプ16',
        ['Eagle\'s Fury'] = '怒れるイーグル',
        ['Emblem of Freedom'] = '自由の記章',
        ['Eternal Corona'] = '永遠の光冠',
        ['Executioner\'s Canopy'] = '処刑者のキャノピー',
        ['Eye of Freedom'] = 'アイ・オブ・フリーダム',
        ['Eye of Liberty'] = 'アイ・オブ・リバティ',
        ['Eye of the Clandestine'] = '秘密の眼',
        ['FS-05 Marksman'] = 'FS-05 マークスマン',
        ['FS-11 Executioner'] = 'FS-11 エクセキューショナー',
        ['FS-23 Battle Master'] = 'FS-23 バトルマスター',
        ['FS-34 Exterminator'] = 'FS-34 エクスターミネーター',
        ['FS-37 Ravager'] = 'FS-37 ラベジャー',
        ['FS-38 Eradicator'] = 'FS-38 エラディケーター',
        ['FS-55 Devastator'] = 'FS-55 デバステーター',
        ['FS-61 Dreadnought'] = 'FS-61 ドレッドノート',
        ['Fallen Hero\'s Vengeance'] = '敗れし英雄の復讐',
        ['Federation\'s Embrace'] = '連邦の抱擁',
        ['Foe Rent Asunder'] = '引き裂かれたる敵',
        ['Foesmasher'] = '殲滅者',
        ['Fre Liberam'] = '自由なる道',
        ['Free-Spirited Spangles'] = '自由な魂の輝き',
        ['Freedom\'s Tapestry'] = '自由のタペストリー',
        ['GS-11 Democracy\'s Deputy'] = 'GS-11 民主主義の法務官',
        ['GS-17 Frontier Marshal'] = 'GS-17 辺境の守護者',
        ['GS-66 Lawmaker'] = 'GS-66 立法者',
        ['Gilded Quill'] = '金色の羽根',
        ['Greatcloak of Rebar Resolve'] = '鉄心のグレートマント',
        ['Harbinger of True Equality'] = '平等の先駆者',
        ['Holder of the Yellow Line'] = '黄色い防衛線',
        ['Honored Heirloom'] = '誉れ高き家宝',
        ['Humble Regalia'] = '慎ましいレガリア',
        ['I-09 Heatseeker'] = 'I-09 ヒートシーカー',
        ['I-102 Draconaught'] = 'I-102 ドラコノート',
        ['I-44 Salamander'] = 'I-44 サラマンダー',
        ['I-92 Fire Fighter'] = 'I-92 ファイヤーファイター',
        ['IE-12 Righteous'] = 'IE-12 正義の使者',
        ['IE-3 Martyr'] = 'IE-3 殉難の士',
        ['IE-57 Hell-Bent'] = 'IE-57 ヘルベント',
        ['Independence Bringer'] = '独立をもたらす者',
        ['Infiltrator'] = '潜入者',
        ['Ingress-81'] = '可能性の軌跡-81',
        ['Ix-Voidwalker'] = 'Ix-ヴォイドウォーカー',
        ['Judgment Day'] = '審判の日',
        ['Justice For All'] = '万人に正義を',
        ['KDM-500 Outrider'] = 'KDM-500 アウトライダー',
        ['KDM-73 Dragoon'] = 'KDM-73 ドラグーン',
        ['KDM-763 Pacesetter'] = 'KDM-763 ペースセッター',
        ['Liberty\'s Herald'] = '自由の先駆け',
        ['Light of Eternal Liberty'] = '永遠の自由の光',
        ['Mantle of True Citizenship'] = '真の市民のマント',
        ['Mark of the Constrictor'] = '締め上げる者の印',
        ['Mark of the Crimson Fang'] = '紅牙の印',
        ['Martyris Rex'] = '殉教者の王',
        ['Message of Morale'] = '士気高揚の訴え',
        ['Miranda\'s Legacy'] = 'ミランダの遺産',
        ['Mother Eagle\'s Wings'] = '母なる大鷹の翼',
        ['O-2 Heavy Operator'] = 'O-2 ヘビーオペレーター',
        ['O-3 Free Spirit'] = 'O-3 フリースピリット',
        ['O-44 Bonded Pilot'] = 'O-44 公認パイロット',
        ['Order of the Venerated Ballot'] = '聖票守護団',
        ['Over Artifice Triumphant'] = '謀略への勝利',
        ['PH-202 Twigsnapper'] = 'PH-202 トゥウィッグスナッパー',
        ['PH-56 Jaguar'] = 'PH-56 ジャガー',
        ['PH-9 Predator'] = 'PH-9 プレデター',
        ['Patient Zero\'s Rememberance'] = 'ゼロ号患者への追悼',
        ['Patriot Blue'] = '愛国者の青',
        ['Per Democrasum'] = '民主主義の名の下に',
        ['Pillar of the Abyss'] = '深淵の柱',
        ['Pillars of Freedom'] = '自由を支えるもの',
        ['Pinions of Everlasting Glory'] = '不滅の栄光の立役者',
        ['Podium of Prosperity'] = '繁栄の表彰台',
        ['Pride of the Whistleblower'] = '密告者の誇り',
        ['Proof of Faultless Virtue'] = '欠点なき美徳の証',
        ['Prosperous Green'] = '繁栄の緑',
        ['Protector of the Heart'] = '心臓の守護者',
        ['Proud Gold'] = '誇り高き黄金',
        ['Purifying Eclipse'] = '浄化の蝕',
        ['RE-1861 Parade Commander'] = 'RE-1861 行進隊長',
        ['RE-2310 Honorary Guard'] = 'RE-2310 衛兵',
        ['RE-824 Bearer of the Standard'] = 'RE-824 先導者',
        ['RS-100 Sanctioner'] = 'RS-100 サンクショナー',
        ['RS-20 Constrictor'] = 'RS-20 コンストリクター',
        ['RS-40 Beast of Prey'] = 'RS-40 狩猟獣',
        ['RS-6 Fiend Destroyer'] = 'RS-6 フィンド・デストロイヤー',
        ['RS-67 Null Cipher'] = 'RS-67 ヌルサイファー',
        ['RS-89 Shadow Paragon'] = 'RS-89 シャドウパラゴン',
        ['Rags of the Fashionable'] = '上流階級の布',
        ['Reaper of Bounties'] = '投票権稼ぎ',
        ['Reckoning\'s Cheer'] = '粛清の歓喜',
        ['Red Planet\'s Memory'] = '赤い惑星の記憶',
        ['Rightful Occupier'] = '正当な占有者',
        ['SA-04 Combat Technician'] = 'SA-04 コンバットテクニシャン',
        ['SA-12 Servo-Assisted'] = 'SA-12 サーボアシスト付',
        ['SA-25 Steel Trooper'] = 'SA-25 スチールトルーパー',
        ['SA-32 Dynamo'] = 'SA-32 ダイナモ',
        ['SA-7 Headfirst'] = 'SA-7 ヘッドファースト',
        ['SA-8 Ram'] = 'SA-8 ラム',
        ['SC-15 Drone Master'] = 'SC-15 ドローンマスター',
        ['SC-30 Trailblazer Scout'] = 'SC-30 トレイルブレイザースカウト',
        ['SC-34 Infiltrator'] = 'SC-34 インフィルトレーター',
        ['SC-37 Legionnaire'] = 'SC-37 リージョネア',
        ['SR-18 Roadblock'] = 'SR-18 ロードブロック',
        ['SR-24 Street Scout'] = 'SR-24 ストリート・スカウト',
        ['SR-64 Cinderblock'] = 'SR-64 シンダーブロック',
        ['Schema Laid Bare'] = '暴かれた図式',
        ['Scraps of Sovereignty'] = '主権の小切れ',
        ['Seal of General Consensus'] = 'コンセンサス将軍の印',
        ['Shroud of the Juggernaut'] = 'シュラウド・オブ・ジャガーノート',
        ['Standard of Rapid Evacuation'] = '迅速避難の基準',
        ['Standard of Safe Distance'] = '安全距離基準',
        ['Stone-Wrought Perseverance'] = '石の忍耐',
        ['Strength in Our Arms'] = '力の源',
        ['TG-122 Demo-Trooper'] = 'TG-122 デモ・トルーパー',
        ['TG-8 Sharpshooter'] = 'TG-8 狙撃兵',
        ['TR-117 Alpha Commander'] = 'TR-117 アルファコマンダー',
        ['TR-40 Gold Eagle'] = 'TR-40 ゴールドイーグル',
        ['TR-62 Knight'] = 'TR-62 ナイト',
        ['TR-7 Ambassador of the Brand'] = 'TR-7 ブランド・アンバサダー',
        ['TR-9 Cavalier of Democracy'] = 'TR-9 キャバリア―・オブ・デモクラシー',
        ['Testament to Attrition'] = '消耗戦の証',
        ['The Breach'] = 'ザ・ブリーチ',
        ['The Cape of Stars and Suffrage'] = '星と参政権のマント',
        ['Thundering Hooves of Loyalty'] = '雷鳴轟く忠誠の蹄',
        ['Tideturner'] = '反撃ののろし',
        ['Tread of Liberty'] = '自由の歩み',
        ['Triangulation Veil'] = '三角分割のヴェール',
        ['Tyranny\'s Bane'] = '暴政の終焉',
        ['Tyrant Hunter'] = '暴君ハンター',
        ['UF-16 Inspector'] = 'UF-16 インスペクター',
        ['UF-50 Bloodhound'] = 'UF-50 ブラッドハウンド',
        ['UF-84 Doubt Killer'] = 'UF-84 ダウトキラー',
        ['Unblemished Allegiance'] = '穢れなき忠誠',
        ['United in Equality'] = '平等の下の団結',
        ['Vector of Victory'] = '勝利のベクトル',
        ['Veil of the Valorous Vagabond'] = '勇猛な放浪者のヴェール',
        ['Veridical Ideology'] = '真実のイデオロギー',
        ['Veteran\'s Banner'] = '勇士の軍旗',
        ['Vision of Freedom'] = '自由の視野',
        ['Watchful Compatriot'] = '油断なき同胞',
        ['Way of the Bandolier'] = '弾帯の道',
        ['Wedgeful Tricorn'] = 'ウェッジフル・トライコーン',
        ['Will of the People'] = '人民の意志',
        ['Windswept Wayfinder'] = '逆風の開拓者',
        ['Wings of Valor'] = '武勇の翼',
    },

    -- ---------------------------------------------------------------- 字形がない文字の代用
    -- ゲームのUIフォントに無い記号は、ここのASCII代用に置き換えます。
    -- 文字そのものがない場合は、その行は英語のままになります。
    fallback = {
        ['「'] = '"',  ['」'] = '"',
        ['（'] = '(',  ['）'] = ')',
        ['、'] = ',',  ['，'] = ',',
        ['。'] = '.',  ['：'] = ':',  ['；'] = ';',
        ['！'] = '!',  ['？'] = '?',
        ['・'] = '-',  ['―'] = '-',  ['～'] = '~',  ['〜'] = '~',
        ['→'] = '>',
    },
}
